// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Git
{
    /// <summary>
    /// Tracks a branch's base ref within a repository, and optionally an ordered patch stack applied on top of it. When `Patches` is set, the resulting commits are force-pushed to the branch on the remote; otherwise this resource only resolves and tracks the observed base ref.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Git = UnMango.Git;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Omits the required_providers block since this example also runs as an
    ///     // acceptance test against an in-process build; see examples/provider/provider.tf.
    ///     // Tracks the "main" branch of a public repository. Safe to run against a
    ///     // repository you don't own; git_branch never pushes.
    ///     var main = new Git.Branch("main", new()
    ///     {
    ///         Repository = new Git.Inputs.BranchRepositoryArgs
    ///         {
    ///             Url = "https://github.com/UnstoppableMango/terraform-provider-git.git",
    ///             Host = "github",
    ///         },
    ///         Name = "main",
    ///         BaseRef = "main",
    ///     });
    /// 
    ///     return new Dictionary&lt;string, object?&gt;
    ///     {
    ///         ["resolvedSha"] = main.BaseSha,
    ///     };
    /// });
    /// ```
    /// </summary>
    [GitResourceType("git:index/branch:Branch")]
    public partial class Branch : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Ref this branch is based on.
        /// </summary>
        [Output("baseRef")]
        public Output<string> BaseRef { get; private set; } = null!;

        /// <summary>
        /// Resolved commit hash of `BaseRef` as of the last read.
        /// </summary>
        [Output("baseSha")]
        public Output<string> BaseSha { get; private set; } = null!;

        /// <summary>
        /// Name of the branch.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// How to handle the branch's remote tip having moved since it was last observed, when pushing the patch stack. `Force` (default) always force-pushes, discarding drift, matching this provider's historical behavior. `Fail` aborts the push instead of clobbering unexpected remote changes; re-run `pulumi up` to pick up the new tip, or resolve the drift manually. Only takes effect when `Patches` is set. Must be one of `Fail` or `Force`.
        /// </summary>
        [Output("onConflict")]
        public Output<string> OnConflict { get; private set; } = null!;

        /// <summary>
        /// Ordered list of patch diffs applied on top of base_ref, in the spirit of quilt push. When set, the resulting commits are force-pushed to the branch on the remote.
        /// </summary>
        [Output("patches")]
        public Output<ImmutableArray<string>> Patches { get; private set; } = null!;

        /// <summary>
        /// Repository the branch belongs to.
        /// </summary>
        [Output("repository")]
        public Output<Outputs.BranchRepository> Repository { get; private set; } = null!;

        /// <summary>
        /// Resolved commit hash the branch currently tracks.
        /// </summary>
        [Output("resolvedRef")]
        public Output<string> ResolvedRef { get; private set; } = null!;


        /// <summary>
        /// Create a Branch resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Branch(string name, BranchArgs args, CustomResourceOptions? options = null)
            : base("git:index/branch:Branch", name, args ?? new BranchArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Branch(string name, Input<string> id, BranchState? state = null, CustomResourceOptions? options = null)
            : base("git:index/branch:Branch", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/UnstoppableMango/pulumi-provider-git",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Branch resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Branch Get(string name, Input<string> id, BranchState? state = null, CustomResourceOptions? options = null)
        {
            return new Branch(name, id, state, options);
        }
    }

    public sealed class BranchArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Ref this branch is based on.
        /// </summary>
        [Input("baseRef", required: true)]
        public Input<string> BaseRef { get; set; } = null!;

        /// <summary>
        /// Name of the branch.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// How to handle the branch's remote tip having moved since it was last observed, when pushing the patch stack. `Force` (default) always force-pushes, discarding drift, matching this provider's historical behavior. `Fail` aborts the push instead of clobbering unexpected remote changes; re-run `pulumi up` to pick up the new tip, or resolve the drift manually. Only takes effect when `Patches` is set. Must be one of `Fail` or `Force`.
        /// </summary>
        [Input("onConflict")]
        public Input<string>? OnConflict { get; set; }

        [Input("patches")]
        private InputList<string>? _patches;

        /// <summary>
        /// Ordered list of patch diffs applied on top of base_ref, in the spirit of quilt push. When set, the resulting commits are force-pushed to the branch on the remote.
        /// </summary>
        public InputList<string> Patches
        {
            get => _patches ?? (_patches = new InputList<string>());
            set => _patches = value;
        }

        /// <summary>
        /// Repository the branch belongs to.
        /// </summary>
        [Input("repository", required: true)]
        public Input<Inputs.BranchRepositoryArgs> Repository { get; set; } = null!;

        public BranchArgs()
        {
        }
        public static new BranchArgs Empty => new BranchArgs();
    }

    public sealed class BranchState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Ref this branch is based on.
        /// </summary>
        [Input("baseRef")]
        public Input<string>? BaseRef { get; set; }

        /// <summary>
        /// Resolved commit hash of `BaseRef` as of the last read.
        /// </summary>
        [Input("baseSha")]
        public Input<string>? BaseSha { get; set; }

        /// <summary>
        /// Name of the branch.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// How to handle the branch's remote tip having moved since it was last observed, when pushing the patch stack. `Force` (default) always force-pushes, discarding drift, matching this provider's historical behavior. `Fail` aborts the push instead of clobbering unexpected remote changes; re-run `pulumi up` to pick up the new tip, or resolve the drift manually. Only takes effect when `Patches` is set. Must be one of `Fail` or `Force`.
        /// </summary>
        [Input("onConflict")]
        public Input<string>? OnConflict { get; set; }

        [Input("patches")]
        private InputList<string>? _patches;

        /// <summary>
        /// Ordered list of patch diffs applied on top of base_ref, in the spirit of quilt push. When set, the resulting commits are force-pushed to the branch on the remote.
        /// </summary>
        public InputList<string> Patches
        {
            get => _patches ?? (_patches = new InputList<string>());
            set => _patches = value;
        }

        /// <summary>
        /// Repository the branch belongs to.
        /// </summary>
        [Input("repository")]
        public Input<Inputs.BranchRepositoryGetArgs>? Repository { get; set; }

        /// <summary>
        /// Resolved commit hash the branch currently tracks.
        /// </summary>
        [Input("resolvedRef")]
        public Input<string>? ResolvedRef { get; set; }

        public BranchState()
        {
        }
        public static new BranchState Empty => new BranchState();
    }
}
