// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Git
{
    public static class GetPatch
    {
        /// <summary>
        /// Resolves a single patch: a local file, inline diff content, or a remote host source (e.g. a GitHub PR/commit or a GitLab MR/commit). Exactly one of `Content`, `File`, `Github`, or `Gitlab` must be set. Does not clone, apply, commit, or push; that is `git.Branch`'s responsibility.
        /// </summary>
        public static Task<GetPatchResult> InvokeAsync(GetPatchArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPatchResult>("git:index/getPatch:getPatch", args ?? new GetPatchArgs(), options.WithDefaults());

        /// <summary>
        /// Resolves a single patch: a local file, inline diff content, or a remote host source (e.g. a GitHub PR/commit or a GitLab MR/commit). Exactly one of `Content`, `File`, `Github`, or `Gitlab` must be set. Does not clone, apply, commit, or push; that is `git.Branch`'s responsibility.
        /// </summary>
        public static Output<GetPatchResult> Invoke(GetPatchInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPatchResult>("git:index/getPatch:getPatch", args ?? new GetPatchInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Resolves a single patch: a local file, inline diff content, or a remote host source (e.g. a GitHub PR/commit or a GitLab MR/commit). Exactly one of `Content`, `File`, `Github`, or `Gitlab` must be set. Does not clone, apply, commit, or push; that is `git.Branch`'s responsibility.
        /// </summary>
        public static Output<GetPatchResult> Invoke(GetPatchInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetPatchResult>("git:index/getPatch:getPatch", args ?? new GetPatchInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPatchArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Authentication details used to call the GitHub or GitLab API when `Github` or `Gitlab` is set.
        /// </summary>
        [Input("auth")]
        public Inputs.GetPatchAuthArgs? Auth { get; set; }

        /// <summary>
        /// Inline unified diff content.
        /// </summary>
        [Input("content")]
        public string? Content { get; set; }

        /// <summary>
        /// Path to a local patch file, read on refresh.
        /// </summary>
        [Input("file")]
        public string? File { get; set; }

        /// <summary>
        /// Resolves the patch from a GitHub pull request or commit. Exactly one of `Pr` or `Commit` must be set.
        /// </summary>
        [Input("github")]
        public Inputs.GetPatchGithubArgs? Github { get; set; }

        /// <summary>
        /// Resolves the patch from a GitLab merge request or commit. Exactly one of `Mr` or `Commit` must be set.
        /// </summary>
        [Input("gitlab")]
        public Inputs.GetPatchGitlabArgs? Gitlab { get; set; }

        public GetPatchArgs()
        {
        }
        public static new GetPatchArgs Empty => new GetPatchArgs();
    }

    public sealed class GetPatchInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Authentication details used to call the GitHub or GitLab API when `Github` or `Gitlab` is set.
        /// </summary>
        [Input("auth")]
        public Input<Inputs.GetPatchAuthInputArgs>? Auth { get; set; }

        /// <summary>
        /// Inline unified diff content.
        /// </summary>
        [Input("content")]
        public Input<string>? Content { get; set; }

        /// <summary>
        /// Path to a local patch file, read on refresh.
        /// </summary>
        [Input("file")]
        public Input<string>? File { get; set; }

        /// <summary>
        /// Resolves the patch from a GitHub pull request or commit. Exactly one of `Pr` or `Commit` must be set.
        /// </summary>
        [Input("github")]
        public Input<Inputs.GetPatchGithubInputArgs>? Github { get; set; }

        /// <summary>
        /// Resolves the patch from a GitLab merge request or commit. Exactly one of `Mr` or `Commit` must be set.
        /// </summary>
        [Input("gitlab")]
        public Input<Inputs.GetPatchGitlabInputArgs>? Gitlab { get; set; }

        public GetPatchInvokeArgs()
        {
        }
        public static new GetPatchInvokeArgs Empty => new GetPatchInvokeArgs();
    }


    [OutputType]
    public sealed class GetPatchResult
    {
        /// <summary>
        /// Authentication details used to call the GitHub or GitLab API when `Github` or `Gitlab` is set.
        /// </summary>
        public readonly Outputs.GetPatchAuthResult? Auth;
        /// <summary>
        /// Inline unified diff content.
        /// </summary>
        public readonly string? Content;
        /// <summary>
        /// Resolved unified diff content, from whichever of `Content`, `File`, or `Github` was set.
        /// </summary>
        public readonly string Diff;
        /// <summary>
        /// Path to a local patch file, read on refresh.
        /// </summary>
        public readonly string? File;
        /// <summary>
        /// Resolves the patch from a GitHub pull request or commit. Exactly one of `Pr` or `Commit` must be set.
        /// </summary>
        public readonly Outputs.GetPatchGithubResult? Github;
        /// <summary>
        /// Resolves the patch from a GitLab merge request or commit. Exactly one of `Mr` or `Commit` must be set.
        /// </summary>
        public readonly Outputs.GetPatchGitlabResult? Gitlab;
        /// <summary>
        /// Stable identifier for the patch: the hex-encoded sha256 of the resolved `Diff`.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetPatchResult(
            Outputs.GetPatchAuthResult? auth,

            string? content,

            string diff,

            string? file,

            Outputs.GetPatchGithubResult? github,

            Outputs.GetPatchGitlabResult? gitlab,

            string id)
        {
            Auth = auth;
            Content = content;
            Diff = diff;
            File = file;
            Github = github;
            Gitlab = gitlab;
            Id = id;
        }
    }
}
