// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Git
{
    public static class GetRepository
    {
        /// <summary>
        /// References an existing repository. Reference-only: this provider never creates or deletes repositories on the host. It resolves connection details (URL, host type, auth) used by other resources.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Git = UnMango.Git;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Omits the required_providers block since this example also runs as an
        ///     // acceptance test against an in-process build; see examples/provider/provider.tf.
        ///     // Resolves and verifies a public repository via ls-remote.
        ///     var @this = Git.GetRepository.Invoke(new()
        ///     {
        ///         Url = "https://github.com/UnstoppableMango/terraform-provider-git.git",
        ///         Host = "github",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["repositoryId"] = @this.Apply(@this =&gt; @this.Apply(getRepositoryResult =&gt; getRepositoryResult.Id)),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetRepositoryResult> InvokeAsync(GetRepositoryArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetRepositoryResult>("git:index/getRepository:getRepository", args ?? new GetRepositoryArgs(), options.WithDefaults());

        /// <summary>
        /// References an existing repository. Reference-only: this provider never creates or deletes repositories on the host. It resolves connection details (URL, host type, auth) used by other resources.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Git = UnMango.Git;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Omits the required_providers block since this example also runs as an
        ///     // acceptance test against an in-process build; see examples/provider/provider.tf.
        ///     // Resolves and verifies a public repository via ls-remote.
        ///     var @this = Git.GetRepository.Invoke(new()
        ///     {
        ///         Url = "https://github.com/UnstoppableMango/terraform-provider-git.git",
        ///         Host = "github",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["repositoryId"] = @this.Apply(@this =&gt; @this.Apply(getRepositoryResult =&gt; getRepositoryResult.Id)),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetRepositoryResult> Invoke(GetRepositoryInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetRepositoryResult>("git:index/getRepository:getRepository", args ?? new GetRepositoryInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// References an existing repository. Reference-only: this provider never creates or deletes repositories on the host. It resolves connection details (URL, host type, auth) used by other resources.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Git = UnMango.Git;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Omits the required_providers block since this example also runs as an
        ///     // acceptance test against an in-process build; see examples/provider/provider.tf.
        ///     // Resolves and verifies a public repository via ls-remote.
        ///     var @this = Git.GetRepository.Invoke(new()
        ///     {
        ///         Url = "https://github.com/UnstoppableMango/terraform-provider-git.git",
        ///         Host = "github",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["repositoryId"] = @this.Apply(@this =&gt; @this.Apply(getRepositoryResult =&gt; getRepositoryResult.Id)),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetRepositoryResult> Invoke(GetRepositoryInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetRepositoryResult>("git:index/getRepository:getRepository", args ?? new GetRepositoryInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetRepositoryArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Authentication details used to connect to the repository.
        /// </summary>
        [Input("auth")]
        public Inputs.GetRepositoryAuthArgs? Auth { get; set; }

        /// <summary>
        /// Type of host the repository is on. Must be one of `Github`, `Gitlab`, or `Generic`.
        /// </summary>
        [Input("host")]
        public string? Host { get; set; }

        /// <summary>
        /// URL of the repository.
        /// </summary>
        [Input("url", required: true)]
        public string Url { get; set; } = null!;

        public GetRepositoryArgs()
        {
        }
        public static new GetRepositoryArgs Empty => new GetRepositoryArgs();
    }

    public sealed class GetRepositoryInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Authentication details used to connect to the repository.
        /// </summary>
        [Input("auth")]
        public Input<Inputs.GetRepositoryAuthInputArgs>? Auth { get; set; }

        /// <summary>
        /// Type of host the repository is on. Must be one of `Github`, `Gitlab`, or `Generic`.
        /// </summary>
        [Input("host")]
        public Input<string>? Host { get; set; }

        /// <summary>
        /// URL of the repository.
        /// </summary>
        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        public GetRepositoryInvokeArgs()
        {
        }
        public static new GetRepositoryInvokeArgs Empty => new GetRepositoryInvokeArgs();
    }


    [OutputType]
    public sealed class GetRepositoryResult
    {
        /// <summary>
        /// Authentication details used to connect to the repository.
        /// </summary>
        public readonly Outputs.GetRepositoryAuthResult? Auth;
        /// <summary>
        /// Type of host the repository is on. Must be one of `Github`, `Gitlab`, or `Generic`.
        /// </summary>
        public readonly string? Host;
        /// <summary>
        /// Identifier for the repository. Mirrors the `Url` attribute.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// URL of the repository.
        /// </summary>
        public readonly string Url;

        [OutputConstructor]
        private GetRepositoryResult(
            Outputs.GetRepositoryAuthResult? auth,

            string? host,

            string id,

            string url)
        {
            Auth = auth;
            Host = host;
            Id = id;
            Url = url;
        }
    }
}
