// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Immutable;

namespace UnMango.Git
{
    public static class Config
    {
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "IDE1006", Justification = 
        "Double underscore prefix used to avoid conflicts with variable names.")]
        private sealed class __Value<T>
        {
            private readonly Func<T> _getter;
            private T _value = default!;
            private bool _set;

            public __Value(Func<T> getter)
            {
                _getter = getter;
            }

            public T Get() => _set ? _value : _getter();

            public void Set(T value)
            {
                _value = value;
                _set = true;
            }
        }

        private static readonly global::Pulumi.Config __config = new global::Pulumi.Config("git");

        private static readonly __Value<UnMango.Git.Config.Types.Auth?> _auth = new __Value<UnMango.Git.Config.Types.Auth?>(() => __config.GetObject<UnMango.Git.Config.Types.Auth>("auth"));
        /// <summary>
        /// Default authentication details used to connect to repositories and hosts, applied when a resource or data source does not set its own `auth.token`.
        /// </summary>
        public static UnMango.Git.Config.Types.Auth? Auth
        {
            get => _auth.Get();
            set => _auth.Set(value);
        }

        private static readonly __Value<string?> _gitImplementation = new __Value<string?>(() => __config.Get("gitImplementation"));
        /// <summary>
        /// Git implementation backend to use. Must be one of `go-git` or `Exec`. Defaults to `go-git`.
        /// </summary>
        public static string? GitImplementation
        {
            get => _gitImplementation.Get();
            set => _gitImplementation.Set(value);
        }

        public static class Types
        {

             public class Auth
             {
            /// <summary>
            /// Default token used to authenticate with a repository host, unless overridden per-resource.
            /// </summary>
                public string? Token { get; set; } = null!;
            }
        }
    }
}
