# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

auth: Optional[str]
"""
Default authentication details used to connect to repositories and hosts, applied when a resource or data source does not set its own `auth.token`.
"""

gitImplementation: Optional[str]
"""
Git implementation backend to use. Must be one of `go-git` or `exec`. Defaults to `go-git`.
"""

