# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'Auth',
]

@pulumi.output_type
class Auth(dict):
    def __init__(__self__, *,
                 token: Optional[_builtins.str] = None):
        """
        :param _builtins.str token: Default token used to authenticate with a repository host, unless overridden per-resource.
        """
        if token is not None:
            pulumi.set(__self__, "token", token)

    @_builtins.property
    @pulumi.getter
    def token(self) -> Optional[_builtins.str]:
        """
        Default token used to authenticate with a repository host, unless overridden per-resource.
        """
        return pulumi.get(self, "token")


