// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("git");

/**
 * Default authentication details used to connect to repositories and hosts, applied when a resource or data source does not set its own `auth.token`.
 */
export declare const auth: outputs.config.Auth | undefined;
Object.defineProperty(exports, "auth", {
    get() {
        return __config.getObject<outputs.config.Auth>("auth");
    },
    enumerable: true,
});

/**
 * Git implementation backend to use. Must be one of `go-git` or `exec`. Defaults to `go-git`.
 */
export declare const gitImplementation: string | undefined;
Object.defineProperty(exports, "gitImplementation", {
    get() {
        return __config.get("gitImplementation");
    },
    enumerable: true,
});

