// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Git.Outputs
{

    [OutputType]
    public sealed class BranchRepositoryAuth
    {
        /// <summary>
        /// Token used to authenticate with the repository host.
        /// </summary>
        public readonly string? Token;

        [OutputConstructor]
        private BranchRepositoryAuth(string? token)
        {
            Token = token;
        }
    }
}
