// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Git.Outputs
{

    [OutputType]
    public sealed class BranchRepository
    {
        /// <summary>
        /// Authentication details used to connect to the repository.
        /// </summary>
        public readonly Outputs.BranchRepositoryAuth? Auth;
        /// <summary>
        /// Type of host the repository is on. Must be one of `Github`, `Gitlab`, or `Generic`.
        /// </summary>
        public readonly string? Host;
        /// <summary>
        /// URL of the repository.
        /// </summary>
        public readonly string Url;

        [OutputConstructor]
        private BranchRepository(
            Outputs.BranchRepositoryAuth? auth,

            string? host,

            string url)
        {
            Auth = auth;
            Host = host;
            Url = url;
        }
    }
}
