// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Git.Outputs
{

    [OutputType]
    public sealed class GetPatchGithubResult
    {
        /// <summary>
        /// Commit sha to resolve the patch from.
        /// </summary>
        public readonly string? Commit;
        /// <summary>
        /// Pull request number to resolve the patch from.
        /// </summary>
        public readonly int? Pr;
        /// <summary>
        /// Repository the pull request or commit belongs to, in `owner/name` form.
        /// </summary>
        public readonly string Repository;
        /// <summary>
        /// Resolved commit sha (the pull request's head commit, or `Commit` itself).
        /// </summary>
        public readonly string Sha;

        [OutputConstructor]
        private GetPatchGithubResult(
            string? commit,

            int? pr,

            string repository,

            string sha)
        {
            Commit = commit;
            Pr = pr;
            Repository = repository;
            Sha = sha;
        }
    }
}
