// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Git.Outputs
{

    [OutputType]
    public sealed class GetPatchGitlabResult
    {
        /// <summary>
        /// Commit sha to resolve the patch from.
        /// </summary>
        public readonly string? Commit;
        /// <summary>
        /// Merge request IID to resolve the patch from.
        /// </summary>
        public readonly int? Mr;
        /// <summary>
        /// Project the merge request or commit belongs to, as a GitLab project path (e.g. `group/project`) or numeric ID.
        /// </summary>
        public readonly string Project;
        /// <summary>
        /// Resolved commit sha (the merge request's head commit, or `Commit` itself).
        /// </summary>
        public readonly string Sha;

        [OutputConstructor]
        private GetPatchGitlabResult(
            string? commit,

            int? mr,

            string project,

            string sha)
        {
            Commit = commit;
            Mr = mr;
            Project = project;
            Sha = sha;
        }
    }
}
