// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/UnstoppableMango/pulumi-provider-git/sdk/go/git/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Default authentication details used to connect to repositories and hosts, applied when a resource or data source does not set its own `auth.token`.
func GetAuth(ctx *pulumi.Context) string {
	return config.Get(ctx, "git:auth")
}

// Git implementation backend to use. Must be one of `go-git` or `exec`. Defaults to `go-git`.
func GetGitImplementation(ctx *pulumi.Context) string {
	return config.Get(ctx, "git:gitImplementation")
}
