// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"context"
	"reflect"

	"github.com/UnstoppableMango/pulumi-provider-git/sdk/go/git/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type Auth struct {
	// Default token used to authenticate with a repository host, unless overridden per-resource.
	Token *string `pulumi:"token"`
}

// AuthInput is an input type that accepts AuthArgs and AuthOutput values.
// You can construct a concrete instance of `AuthInput` via:
//
//	AuthArgs{...}
type AuthInput interface {
	pulumi.Input

	ToAuthOutput() AuthOutput
	ToAuthOutputWithContext(context.Context) AuthOutput
}

type AuthArgs struct {
	// Default token used to authenticate with a repository host, unless overridden per-resource.
	Token pulumi.StringPtrInput `pulumi:"token"`
}

func (AuthArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Auth)(nil)).Elem()
}

func (i AuthArgs) ToAuthOutput() AuthOutput {
	return i.ToAuthOutputWithContext(context.Background())
}

func (i AuthArgs) ToAuthOutputWithContext(ctx context.Context) AuthOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AuthOutput)
}

type AuthOutput struct{ *pulumi.OutputState }

func (AuthOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Auth)(nil)).Elem()
}

func (o AuthOutput) ToAuthOutput() AuthOutput {
	return o
}

func (o AuthOutput) ToAuthOutputWithContext(ctx context.Context) AuthOutput {
	return o
}

// Default token used to authenticate with a repository host, unless overridden per-resource.
func (o AuthOutput) Token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Auth) *string { return v.Token }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AuthInput)(nil)).Elem(), AuthArgs{})
	pulumi.RegisterOutputType(AuthOutput{})
}
