// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface BranchRepository {
    /**
     * Authentication details used to connect to the repository.
     */
    auth?: pulumi.Input<inputs.BranchRepositoryAuth | undefined>;
    /**
     * Type of host the repository is on. Must be one of `github`, `gitlab`, or `generic`.
     */
    host?: pulumi.Input<string | undefined>;
    /**
     * URL of the repository.
     */
    url: pulumi.Input<string>;
}

export interface BranchRepositoryAuth {
    /**
     * Token used to authenticate with the repository host.
     */
    token?: pulumi.Input<string | undefined>;
}

export interface GetPatchAuth {
    /**
     * Token used to authenticate with the GitHub or GitLab API.
     */
    token?: string;
}

export interface GetPatchAuthArgs {
    /**
     * Token used to authenticate with the GitHub or GitLab API.
     */
    token?: pulumi.Input<string | undefined>;
}

export interface GetPatchGithub {
    /**
     * Commit sha to resolve the patch from.
     */
    commit?: string;
    /**
     * Pull request number to resolve the patch from.
     */
    pr?: number;
    /**
     * Repository the pull request or commit belongs to, in `owner/name` form.
     */
    repository: string;
    /**
     * Resolved commit sha (the pull request's head commit, or `commit` itself).
     */
    sha?: string;
}

export interface GetPatchGithubArgs {
    /**
     * Commit sha to resolve the patch from.
     */
    commit?: pulumi.Input<string | undefined>;
    /**
     * Pull request number to resolve the patch from.
     */
    pr?: pulumi.Input<number | undefined>;
    /**
     * Repository the pull request or commit belongs to, in `owner/name` form.
     */
    repository: pulumi.Input<string>;
    /**
     * Resolved commit sha (the pull request's head commit, or `commit` itself).
     */
    sha?: pulumi.Input<string | undefined>;
}

export interface GetPatchGitlab {
    /**
     * Commit sha to resolve the patch from.
     */
    commit?: string;
    /**
     * Merge request IID to resolve the patch from.
     */
    mr?: number;
    /**
     * Project the merge request or commit belongs to, as a GitLab project path (e.g. `group/project`) or numeric ID.
     */
    project: string;
    /**
     * Resolved commit sha (the merge request's head commit, or `commit` itself).
     */
    sha?: string;
}

export interface GetPatchGitlabArgs {
    /**
     * Commit sha to resolve the patch from.
     */
    commit?: pulumi.Input<string | undefined>;
    /**
     * Merge request IID to resolve the patch from.
     */
    mr?: pulumi.Input<number | undefined>;
    /**
     * Project the merge request or commit belongs to, as a GitLab project path (e.g. `group/project`) or numeric ID.
     */
    project: pulumi.Input<string>;
    /**
     * Resolved commit sha (the merge request's head commit, or `commit` itself).
     */
    sha?: pulumi.Input<string | undefined>;
}

export interface GetRepositoryAuth {
    /**
     * Token used to authenticate with the repository host.
     */
    token?: string;
}

export interface GetRepositoryAuthArgs {
    /**
     * Token used to authenticate with the repository host.
     */
    token?: pulumi.Input<string | undefined>;
}

export interface ProviderAuth {
    /**
     * Default token used to authenticate with a repository host, unless overridden per-resource.
     */
    token?: pulumi.Input<string | undefined>;
}
export namespace config {
}
