# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .branch import *
from .get_patch import *
from .get_repository import *
from .provider import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_git.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_git.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "git",
  "mod": "index/branch",
  "fqn": "pulumi_git",
  "classes": {
   "git:index/branch:Branch": "Branch"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "git",
  "token": "pulumi:providers:git",
  "fqn": "pulumi_git",
  "class": "Provider"
 }
]
"""
)
