# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'BranchRepositoryArgs',
    'BranchRepositoryArgsDict',
    'BranchRepositoryAuthArgs',
    'BranchRepositoryAuthArgsDict',
    'ProviderAuthArgs',
    'ProviderAuthArgsDict',
    'GetPatchAuthArgs',
    'GetPatchAuthArgsDict',
    'GetPatchGithubArgs',
    'GetPatchGithubArgsDict',
    'GetPatchGitlabArgs',
    'GetPatchGitlabArgsDict',
    'GetRepositoryAuthArgs',
    'GetRepositoryAuthArgsDict',
]

class BranchRepositoryArgsDict(TypedDict):
    url: pulumi.Input[_builtins.str]
    """
    URL of the repository.
    """
    auth: NotRequired[pulumi.Input[Optional['BranchRepositoryAuthArgsDict']]]
    """
    Authentication details used to connect to the repository.
    """
    host: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    Type of host the repository is on. Must be one of `github`, `gitlab`, or `generic`.
    """

@pulumi.input_type
class BranchRepositoryArgs:
    def __init__(__self__, *,
                 url: pulumi.Input[_builtins.str],
                 auth: pulumi.Input[Optional['BranchRepositoryAuthArgs']] = None,
                 host: pulumi.Input[Optional[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] url: URL of the repository.
        :param pulumi.Input['BranchRepositoryAuthArgs'] auth: Authentication details used to connect to the repository.
        :param pulumi.Input[_builtins.str] host: Type of host the repository is on. Must be one of `github`, `gitlab`, or `generic`.
        """
        pulumi.set(__self__, "url", url)
        if auth is not None:
            pulumi.set(__self__, "auth", auth)
        if host is not None:
            pulumi.set(__self__, "host", host)

    @_builtins.property
    @pulumi.getter
    def url(self) -> pulumi.Input[_builtins.str]:
        """
        URL of the repository.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "url", value)

    @_builtins.property
    @pulumi.getter
    def auth(self) -> pulumi.Input[Optional['BranchRepositoryAuthArgs']]:
        """
        Authentication details used to connect to the repository.
        """
        return pulumi.get(self, "auth")

    @auth.setter
    def auth(self, value: pulumi.Input[Optional['BranchRepositoryAuthArgs']]):
        pulumi.set(self, "auth", value)

    @_builtins.property
    @pulumi.getter
    def host(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Type of host the repository is on. Must be one of `github`, `gitlab`, or `generic`.
        """
        return pulumi.get(self, "host")

    @host.setter
    def host(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "host", value)


class BranchRepositoryAuthArgsDict(TypedDict):
    token: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    Token used to authenticate with the repository host.
    """

@pulumi.input_type
class BranchRepositoryAuthArgs:
    def __init__(__self__, *,
                 token: pulumi.Input[Optional[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] token: Token used to authenticate with the repository host.
        """
        if token is not None:
            pulumi.set(__self__, "token", token)

    @_builtins.property
    @pulumi.getter
    def token(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Token used to authenticate with the repository host.
        """
        return pulumi.get(self, "token")

    @token.setter
    def token(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "token", value)


class ProviderAuthArgsDict(TypedDict):
    token: NotRequired[pulumi.Input[Optional[_builtins.str]]]
    """
    Default token used to authenticate with a repository host, unless overridden per-resource.
    """

@pulumi.input_type
class ProviderAuthArgs:
    def __init__(__self__, *,
                 token: pulumi.Input[Optional[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] token: Default token used to authenticate with a repository host, unless overridden per-resource.
        """
        if token is not None:
            pulumi.set(__self__, "token", token)

    @_builtins.property
    @pulumi.getter
    def token(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Default token used to authenticate with a repository host, unless overridden per-resource.
        """
        return pulumi.get(self, "token")

    @token.setter
    def token(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "token", value)


class GetPatchAuthArgsDict(TypedDict):
    token: NotRequired[_builtins.str]
    """
    Token used to authenticate with the GitHub or GitLab API.
    """

@pulumi.input_type
class GetPatchAuthArgs:
    def __init__(__self__, *,
                 token: Optional[_builtins.str] = None):
        """
        :param _builtins.str token: Token used to authenticate with the GitHub or GitLab API.
        """
        if token is not None:
            pulumi.set(__self__, "token", token)

    @_builtins.property
    @pulumi.getter
    def token(self) -> Optional[_builtins.str]:
        """
        Token used to authenticate with the GitHub or GitLab API.
        """
        return pulumi.get(self, "token")

    @token.setter
    def token(self, value: Optional[_builtins.str]):
        pulumi.set(self, "token", value)


class GetPatchGithubArgsDict(TypedDict):
    repository: _builtins.str
    """
    Repository the pull request or commit belongs to, in `owner/name` form.
    """
    sha: _builtins.str
    """
    Resolved commit sha (the pull request's head commit, or `commit` itself).
    """
    commit: NotRequired[_builtins.str]
    """
    Commit sha to resolve the patch from.
    """
    pr: NotRequired[_builtins.int]
    """
    Pull request number to resolve the patch from.
    """

@pulumi.input_type
class GetPatchGithubArgs:
    def __init__(__self__, *,
                 repository: _builtins.str,
                 sha: _builtins.str,
                 commit: Optional[_builtins.str] = None,
                 pr: Optional[_builtins.int] = None):
        """
        :param _builtins.str repository: Repository the pull request or commit belongs to, in `owner/name` form.
        :param _builtins.str sha: Resolved commit sha (the pull request's head commit, or `commit` itself).
        :param _builtins.str commit: Commit sha to resolve the patch from.
        :param _builtins.int pr: Pull request number to resolve the patch from.
        """
        pulumi.set(__self__, "repository", repository)
        pulumi.set(__self__, "sha", sha)
        if commit is not None:
            pulumi.set(__self__, "commit", commit)
        if pr is not None:
            pulumi.set(__self__, "pr", pr)

    @_builtins.property
    @pulumi.getter
    def repository(self) -> _builtins.str:
        """
        Repository the pull request or commit belongs to, in `owner/name` form.
        """
        return pulumi.get(self, "repository")

    @repository.setter
    def repository(self, value: _builtins.str):
        pulumi.set(self, "repository", value)

    @_builtins.property
    @pulumi.getter
    def sha(self) -> _builtins.str:
        """
        Resolved commit sha (the pull request's head commit, or `commit` itself).
        """
        return pulumi.get(self, "sha")

    @sha.setter
    def sha(self, value: _builtins.str):
        pulumi.set(self, "sha", value)

    @_builtins.property
    @pulumi.getter
    def commit(self) -> Optional[_builtins.str]:
        """
        Commit sha to resolve the patch from.
        """
        return pulumi.get(self, "commit")

    @commit.setter
    def commit(self, value: Optional[_builtins.str]):
        pulumi.set(self, "commit", value)

    @_builtins.property
    @pulumi.getter
    def pr(self) -> Optional[_builtins.int]:
        """
        Pull request number to resolve the patch from.
        """
        return pulumi.get(self, "pr")

    @pr.setter
    def pr(self, value: Optional[_builtins.int]):
        pulumi.set(self, "pr", value)


class GetPatchGitlabArgsDict(TypedDict):
    project: _builtins.str
    """
    Project the merge request or commit belongs to, as a GitLab project path (e.g. `group/project`) or numeric ID.
    """
    sha: _builtins.str
    """
    Resolved commit sha (the merge request's head commit, or `commit` itself).
    """
    commit: NotRequired[_builtins.str]
    """
    Commit sha to resolve the patch from.
    """
    mr: NotRequired[_builtins.int]
    """
    Merge request IID to resolve the patch from.
    """

@pulumi.input_type
class GetPatchGitlabArgs:
    def __init__(__self__, *,
                 project: _builtins.str,
                 sha: _builtins.str,
                 commit: Optional[_builtins.str] = None,
                 mr: Optional[_builtins.int] = None):
        """
        :param _builtins.str project: Project the merge request or commit belongs to, as a GitLab project path (e.g. `group/project`) or numeric ID.
        :param _builtins.str sha: Resolved commit sha (the merge request's head commit, or `commit` itself).
        :param _builtins.str commit: Commit sha to resolve the patch from.
        :param _builtins.int mr: Merge request IID to resolve the patch from.
        """
        pulumi.set(__self__, "project", project)
        pulumi.set(__self__, "sha", sha)
        if commit is not None:
            pulumi.set(__self__, "commit", commit)
        if mr is not None:
            pulumi.set(__self__, "mr", mr)

    @_builtins.property
    @pulumi.getter
    def project(self) -> _builtins.str:
        """
        Project the merge request or commit belongs to, as a GitLab project path (e.g. `group/project`) or numeric ID.
        """
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: _builtins.str):
        pulumi.set(self, "project", value)

    @_builtins.property
    @pulumi.getter
    def sha(self) -> _builtins.str:
        """
        Resolved commit sha (the merge request's head commit, or `commit` itself).
        """
        return pulumi.get(self, "sha")

    @sha.setter
    def sha(self, value: _builtins.str):
        pulumi.set(self, "sha", value)

    @_builtins.property
    @pulumi.getter
    def commit(self) -> Optional[_builtins.str]:
        """
        Commit sha to resolve the patch from.
        """
        return pulumi.get(self, "commit")

    @commit.setter
    def commit(self, value: Optional[_builtins.str]):
        pulumi.set(self, "commit", value)

    @_builtins.property
    @pulumi.getter
    def mr(self) -> Optional[_builtins.int]:
        """
        Merge request IID to resolve the patch from.
        """
        return pulumi.get(self, "mr")

    @mr.setter
    def mr(self, value: Optional[_builtins.int]):
        pulumi.set(self, "mr", value)


class GetRepositoryAuthArgsDict(TypedDict):
    token: NotRequired[_builtins.str]
    """
    Token used to authenticate with the repository host.
    """

@pulumi.input_type
class GetRepositoryAuthArgs:
    def __init__(__self__, *,
                 token: Optional[_builtins.str] = None):
        """
        :param _builtins.str token: Token used to authenticate with the repository host.
        """
        if token is not None:
            pulumi.set(__self__, "token", token)

    @_builtins.property
    @pulumi.getter
    def token(self) -> Optional[_builtins.str]:
        """
        Token used to authenticate with the repository host.
        """
        return pulumi.get(self, "token")

    @token.setter
    def token(self, value: Optional[_builtins.str]):
        pulumi.set(self, "token", value)


