# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['BranchArgs', 'Branch']

@pulumi.input_type
class BranchArgs:
    def __init__(__self__, *,
                 base_ref: pulumi.Input[_builtins.str],
                 repository: pulumi.Input['BranchRepositoryArgs'],
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 on_conflict: pulumi.Input[Optional[_builtins.str]] = None,
                 patches: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a Branch resource.

        :param pulumi.Input[_builtins.str] base_ref: Ref this branch is based on.
        :param pulumi.Input['BranchRepositoryArgs'] repository: Repository the branch belongs to.
        :param pulumi.Input[_builtins.str] name: Name of the branch.
        :param pulumi.Input[_builtins.str] on_conflict: How to handle the branch's remote tip having moved since it was last observed, when pushing the patch stack. `force` (default) always force-pushes, discarding drift, matching this provider's historical behavior. `fail` aborts the push instead of clobbering unexpected remote changes; re-run `pulumi up` to pick up the new tip, or resolve the drift manually. Only takes effect when `patches` is set. Must be one of `fail` or `force`.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] patches: Ordered list of patch diffs applied on top of base_ref, in the spirit of quilt push. When set, the resulting commits are force-pushed to the branch on the remote.
        """
        pulumi.set(__self__, "base_ref", base_ref)
        pulumi.set(__self__, "repository", repository)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if on_conflict is not None:
            pulumi.set(__self__, "on_conflict", on_conflict)
        if patches is not None:
            pulumi.set(__self__, "patches", patches)

    @_builtins.property
    @pulumi.getter(name="baseRef")
    def base_ref(self) -> pulumi.Input[_builtins.str]:
        """
        Ref this branch is based on.
        """
        return pulumi.get(self, "base_ref")

    @base_ref.setter
    def base_ref(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "base_ref", value)

    @_builtins.property
    @pulumi.getter
    def repository(self) -> pulumi.Input['BranchRepositoryArgs']:
        """
        Repository the branch belongs to.
        """
        return pulumi.get(self, "repository")

    @repository.setter
    def repository(self, value: pulumi.Input['BranchRepositoryArgs']):
        pulumi.set(self, "repository", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the branch.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="onConflict")
    def on_conflict(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        How to handle the branch's remote tip having moved since it was last observed, when pushing the patch stack. `force` (default) always force-pushes, discarding drift, matching this provider's historical behavior. `fail` aborts the push instead of clobbering unexpected remote changes; re-run `pulumi up` to pick up the new tip, or resolve the drift manually. Only takes effect when `patches` is set. Must be one of `fail` or `force`.
        """
        return pulumi.get(self, "on_conflict")

    @on_conflict.setter
    def on_conflict(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "on_conflict", value)

    @_builtins.property
    @pulumi.getter
    def patches(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Ordered list of patch diffs applied on top of base_ref, in the spirit of quilt push. When set, the resulting commits are force-pushed to the branch on the remote.
        """
        return pulumi.get(self, "patches")

    @patches.setter
    def patches(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "patches", value)


@pulumi.input_type
class _BranchState:
    def __init__(__self__, *,
                 base_ref: pulumi.Input[Optional[_builtins.str]] = None,
                 base_sha: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 on_conflict: pulumi.Input[Optional[_builtins.str]] = None,
                 patches: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 repository: pulumi.Input[Optional['BranchRepositoryArgs']] = None,
                 resolved_ref: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Branch resources.

        :param pulumi.Input[_builtins.str] base_ref: Ref this branch is based on.
        :param pulumi.Input[_builtins.str] base_sha: Resolved commit hash of `base_ref` as of the last read.
        :param pulumi.Input[_builtins.str] name: Name of the branch.
        :param pulumi.Input[_builtins.str] on_conflict: How to handle the branch's remote tip having moved since it was last observed, when pushing the patch stack. `force` (default) always force-pushes, discarding drift, matching this provider's historical behavior. `fail` aborts the push instead of clobbering unexpected remote changes; re-run `pulumi up` to pick up the new tip, or resolve the drift manually. Only takes effect when `patches` is set. Must be one of `fail` or `force`.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] patches: Ordered list of patch diffs applied on top of base_ref, in the spirit of quilt push. When set, the resulting commits are force-pushed to the branch on the remote.
        :param pulumi.Input['BranchRepositoryArgs'] repository: Repository the branch belongs to.
        :param pulumi.Input[_builtins.str] resolved_ref: Resolved commit hash the branch currently tracks.
        """
        if base_ref is not None:
            pulumi.set(__self__, "base_ref", base_ref)
        if base_sha is not None:
            pulumi.set(__self__, "base_sha", base_sha)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if on_conflict is not None:
            pulumi.set(__self__, "on_conflict", on_conflict)
        if patches is not None:
            pulumi.set(__self__, "patches", patches)
        if repository is not None:
            pulumi.set(__self__, "repository", repository)
        if resolved_ref is not None:
            pulumi.set(__self__, "resolved_ref", resolved_ref)

    @_builtins.property
    @pulumi.getter(name="baseRef")
    def base_ref(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Ref this branch is based on.
        """
        return pulumi.get(self, "base_ref")

    @base_ref.setter
    def base_ref(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "base_ref", value)

    @_builtins.property
    @pulumi.getter(name="baseSha")
    def base_sha(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Resolved commit hash of `base_ref` as of the last read.
        """
        return pulumi.get(self, "base_sha")

    @base_sha.setter
    def base_sha(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "base_sha", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the branch.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="onConflict")
    def on_conflict(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        How to handle the branch's remote tip having moved since it was last observed, when pushing the patch stack. `force` (default) always force-pushes, discarding drift, matching this provider's historical behavior. `fail` aborts the push instead of clobbering unexpected remote changes; re-run `pulumi up` to pick up the new tip, or resolve the drift manually. Only takes effect when `patches` is set. Must be one of `fail` or `force`.
        """
        return pulumi.get(self, "on_conflict")

    @on_conflict.setter
    def on_conflict(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "on_conflict", value)

    @_builtins.property
    @pulumi.getter
    def patches(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Ordered list of patch diffs applied on top of base_ref, in the spirit of quilt push. When set, the resulting commits are force-pushed to the branch on the remote.
        """
        return pulumi.get(self, "patches")

    @patches.setter
    def patches(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "patches", value)

    @_builtins.property
    @pulumi.getter
    def repository(self) -> pulumi.Input[Optional['BranchRepositoryArgs']]:
        """
        Repository the branch belongs to.
        """
        return pulumi.get(self, "repository")

    @repository.setter
    def repository(self, value: pulumi.Input[Optional['BranchRepositoryArgs']]):
        pulumi.set(self, "repository", value)

    @_builtins.property
    @pulumi.getter(name="resolvedRef")
    def resolved_ref(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Resolved commit hash the branch currently tracks.
        """
        return pulumi.get(self, "resolved_ref")

    @resolved_ref.setter
    def resolved_ref(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "resolved_ref", value)


@pulumi.type_token("git:index/branch:Branch")
class Branch(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 base_ref: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 on_conflict: pulumi.Input[Optional[_builtins.str]] = None,
                 patches: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 repository: pulumi.Input[Optional[Union['BranchRepositoryArgs', 'BranchRepositoryArgsDict']]] = None,
                 __props__=None):
        """
        Tracks a branch's base ref within a repository, and optionally an ordered patch stack applied on top of it. When `patches` is set, the resulting commits are force-pushed to the branch on the remote; otherwise this resource only resolves and tracks the observed base ref.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_git as git

        # Omits the required_providers block since this example also runs as an
        # acceptance test against an in-process build; see examples/provider/provider.tf.
        # Tracks the "main" branch of a public repository. Safe to run against a
        # repository you don't own; git_branch never pushes.
        main = git.Branch("main",
            repository={
                "url": "https://github.com/UnstoppableMango/terraform-provider-git.git",
                "host": "github",
            },
            name="main",
            base_ref="main")
        pulumi.export("resolvedSha", main.base_sha)
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] base_ref: Ref this branch is based on.
        :param pulumi.Input[_builtins.str] name: Name of the branch.
        :param pulumi.Input[_builtins.str] on_conflict: How to handle the branch's remote tip having moved since it was last observed, when pushing the patch stack. `force` (default) always force-pushes, discarding drift, matching this provider's historical behavior. `fail` aborts the push instead of clobbering unexpected remote changes; re-run `pulumi up` to pick up the new tip, or resolve the drift manually. Only takes effect when `patches` is set. Must be one of `fail` or `force`.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] patches: Ordered list of patch diffs applied on top of base_ref, in the spirit of quilt push. When set, the resulting commits are force-pushed to the branch on the remote.
        :param pulumi.Input[Union['BranchRepositoryArgs', 'BranchRepositoryArgsDict']] repository: Repository the branch belongs to.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: BranchArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Tracks a branch's base ref within a repository, and optionally an ordered patch stack applied on top of it. When `patches` is set, the resulting commits are force-pushed to the branch on the remote; otherwise this resource only resolves and tracks the observed base ref.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_git as git

        # Omits the required_providers block since this example also runs as an
        # acceptance test against an in-process build; see examples/provider/provider.tf.
        # Tracks the "main" branch of a public repository. Safe to run against a
        # repository you don't own; git_branch never pushes.
        main = git.Branch("main",
            repository={
                "url": "https://github.com/UnstoppableMango/terraform-provider-git.git",
                "host": "github",
            },
            name="main",
            base_ref="main")
        pulumi.export("resolvedSha", main.base_sha)
        ```


        :param str resource_name: The name of the resource.
        :param BranchArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(BranchArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 base_ref: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 on_conflict: pulumi.Input[Optional[_builtins.str]] = None,
                 patches: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 repository: pulumi.Input[Optional[Union['BranchRepositoryArgs', 'BranchRepositoryArgsDict']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = BranchArgs.__new__(BranchArgs)

            if base_ref is None and not opts.urn:
                raise TypeError("Missing required property 'base_ref'")
            __props__.__dict__["base_ref"] = base_ref
            __props__.__dict__["name"] = name
            __props__.__dict__["on_conflict"] = on_conflict
            __props__.__dict__["patches"] = patches
            if repository is None and not opts.urn:
                raise TypeError("Missing required property 'repository'")
            __props__.__dict__["repository"] = repository
            __props__.__dict__["base_sha"] = None
            __props__.__dict__["resolved_ref"] = None
        super(Branch, __self__).__init__(
            'git:index/branch:Branch',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            base_ref: pulumi.Input[Optional[_builtins.str]] = None,
            base_sha: pulumi.Input[Optional[_builtins.str]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            on_conflict: pulumi.Input[Optional[_builtins.str]] = None,
            patches: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            repository: pulumi.Input[Optional[Union['BranchRepositoryArgs', 'BranchRepositoryArgsDict']]] = None,
            resolved_ref: pulumi.Input[Optional[_builtins.str]] = None) -> 'Branch':
        """
        Get an existing Branch resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] base_ref: Ref this branch is based on.
        :param pulumi.Input[_builtins.str] base_sha: Resolved commit hash of `base_ref` as of the last read.
        :param pulumi.Input[_builtins.str] name: Name of the branch.
        :param pulumi.Input[_builtins.str] on_conflict: How to handle the branch's remote tip having moved since it was last observed, when pushing the patch stack. `force` (default) always force-pushes, discarding drift, matching this provider's historical behavior. `fail` aborts the push instead of clobbering unexpected remote changes; re-run `pulumi up` to pick up the new tip, or resolve the drift manually. Only takes effect when `patches` is set. Must be one of `fail` or `force`.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] patches: Ordered list of patch diffs applied on top of base_ref, in the spirit of quilt push. When set, the resulting commits are force-pushed to the branch on the remote.
        :param pulumi.Input[Union['BranchRepositoryArgs', 'BranchRepositoryArgsDict']] repository: Repository the branch belongs to.
        :param pulumi.Input[_builtins.str] resolved_ref: Resolved commit hash the branch currently tracks.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _BranchState.__new__(_BranchState)

        __props__.__dict__["base_ref"] = base_ref
        __props__.__dict__["base_sha"] = base_sha
        __props__.__dict__["name"] = name
        __props__.__dict__["on_conflict"] = on_conflict
        __props__.__dict__["patches"] = patches
        __props__.__dict__["repository"] = repository
        __props__.__dict__["resolved_ref"] = resolved_ref
        return Branch(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="baseRef")
    def base_ref(self) -> pulumi.Output[_builtins.str]:
        """
        Ref this branch is based on.
        """
        return pulumi.get(self, "base_ref")

    @_builtins.property
    @pulumi.getter(name="baseSha")
    def base_sha(self) -> pulumi.Output[_builtins.str]:
        """
        Resolved commit hash of `base_ref` as of the last read.
        """
        return pulumi.get(self, "base_sha")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the branch.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="onConflict")
    def on_conflict(self) -> pulumi.Output[_builtins.str]:
        """
        How to handle the branch's remote tip having moved since it was last observed, when pushing the patch stack. `force` (default) always force-pushes, discarding drift, matching this provider's historical behavior. `fail` aborts the push instead of clobbering unexpected remote changes; re-run `pulumi up` to pick up the new tip, or resolve the drift manually. Only takes effect when `patches` is set. Must be one of `fail` or `force`.
        """
        return pulumi.get(self, "on_conflict")

    @_builtins.property
    @pulumi.getter
    def patches(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Ordered list of patch diffs applied on top of base_ref, in the spirit of quilt push. When set, the resulting commits are force-pushed to the branch on the remote.
        """
        return pulumi.get(self, "patches")

    @_builtins.property
    @pulumi.getter
    def repository(self) -> pulumi.Output['outputs.BranchRepository']:
        """
        Repository the branch belongs to.
        """
        return pulumi.get(self, "repository")

    @_builtins.property
    @pulumi.getter(name="resolvedRef")
    def resolved_ref(self) -> pulumi.Output[_builtins.str]:
        """
        Resolved commit hash the branch currently tracks.
        """
        return pulumi.get(self, "resolved_ref")

