# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetRepositoryResult',
    'AwaitableGetRepositoryResult',
    'get_repository',
    'get_repository_output',
]

@pulumi.output_type
class GetRepositoryResult:
    """
    A collection of values returned by getRepository.
    """
    def __init__(__self__, auth=None, host=None, id=None, url=None):
        if auth and not isinstance(auth, dict):
            raise TypeError("Expected argument 'auth' to be a dict")
        pulumi.set(__self__, "auth", auth)
        if host and not isinstance(host, str):
            raise TypeError("Expected argument 'host' to be a str")
        pulumi.set(__self__, "host", host)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if url and not isinstance(url, str):
            raise TypeError("Expected argument 'url' to be a str")
        pulumi.set(__self__, "url", url)

    @_builtins.property
    @pulumi.getter
    def auth(self) -> Optional['outputs.GetRepositoryAuthResult']:
        """
        Authentication details used to connect to the repository.
        """
        return pulumi.get(self, "auth")

    @_builtins.property
    @pulumi.getter
    def host(self) -> Optional[_builtins.str]:
        """
        Type of host the repository is on. Must be one of `github`, `gitlab`, or `generic`.
        """
        return pulumi.get(self, "host")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        Identifier for the repository. Mirrors the `url` attribute.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def url(self) -> _builtins.str:
        """
        URL of the repository.
        """
        return pulumi.get(self, "url")


class AwaitableGetRepositoryResult(GetRepositoryResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetRepositoryResult(
            auth=self.auth,
            host=self.host,
            id=self.id,
            url=self.url)


def get_repository(auth: Optional[Union['GetRepositoryAuthArgs', 'GetRepositoryAuthArgsDict']] = None,
                   host: Optional[_builtins.str] = None,
                   url: Optional[_builtins.str] = None,
                   opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetRepositoryResult:
    """
    References an existing repository. Reference-only: this provider never creates or deletes repositories on the host. It resolves connection details (URL, host type, auth) used by other resources.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_git as git

    # Omits the required_providers block since this example also runs as an
    # acceptance test against an in-process build; see examples/provider/provider.tf.
    # Resolves and verifies a public repository via ls-remote.
    this = git.get_repository(url="https://github.com/UnstoppableMango/terraform-provider-git.git",
        host="github")
    pulumi.export("repositoryId", this.id)
    ```


    :param Union['GetRepositoryAuthArgs', 'GetRepositoryAuthArgsDict'] auth: Authentication details used to connect to the repository.
    :param _builtins.str host: Type of host the repository is on. Must be one of `github`, `gitlab`, or `generic`.
    :param _builtins.str url: URL of the repository.
    """
    __args__ = dict()
    __args__['auth'] = auth
    __args__['host'] = host
    __args__['url'] = url
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('git:index/getRepository:getRepository', __args__, opts=opts, typ=GetRepositoryResult).value

    return AwaitableGetRepositoryResult(
        auth=pulumi.get(__ret__, 'auth'),
        host=pulumi.get(__ret__, 'host'),
        id=pulumi.get(__ret__, 'id'),
        url=pulumi.get(__ret__, 'url'))
def get_repository_output(auth: pulumi.Input[Optional[Optional[Union['GetRepositoryAuthArgs', 'GetRepositoryAuthArgsDict']]]] = None,
                          host: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                          url: pulumi.Input[Optional[_builtins.str]] = None,
                          opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetRepositoryResult]:
    """
    References an existing repository. Reference-only: this provider never creates or deletes repositories on the host. It resolves connection details (URL, host type, auth) used by other resources.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_git as git

    # Omits the required_providers block since this example also runs as an
    # acceptance test against an in-process build; see examples/provider/provider.tf.
    # Resolves and verifies a public repository via ls-remote.
    this = git.get_repository(url="https://github.com/UnstoppableMango/terraform-provider-git.git",
        host="github")
    pulumi.export("repositoryId", this.id)
    ```


    :param Union['GetRepositoryAuthArgs', 'GetRepositoryAuthArgsDict'] auth: Authentication details used to connect to the repository.
    :param _builtins.str host: Type of host the repository is on. Must be one of `github`, `gitlab`, or `generic`.
    :param _builtins.str url: URL of the repository.
    """
    __args__ = dict()
    __args__['auth'] = auth
    __args__['host'] = host
    __args__['url'] = url
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('git:index/getRepository:getRepository', __args__, opts=opts, typ=GetRepositoryResult)
    return __ret__.apply(lambda __response__: GetRepositoryResult(
        auth=pulumi.get(__response__, 'auth'),
        host=pulumi.get(__response__, 'host'),
        id=pulumi.get(__response__, 'id'),
        url=pulumi.get(__response__, 'url')))
