# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetPatchResult',
    'AwaitableGetPatchResult',
    'get_patch',
    'get_patch_output',
]

@pulumi.output_type
class GetPatchResult:
    """
    A collection of values returned by getPatch.
    """
    def __init__(__self__, auth=None, content=None, diff=None, file=None, github=None, gitlab=None, id=None):
        if auth and not isinstance(auth, dict):
            raise TypeError("Expected argument 'auth' to be a dict")
        pulumi.set(__self__, "auth", auth)
        if content and not isinstance(content, str):
            raise TypeError("Expected argument 'content' to be a str")
        pulumi.set(__self__, "content", content)
        if diff and not isinstance(diff, str):
            raise TypeError("Expected argument 'diff' to be a str")
        pulumi.set(__self__, "diff", diff)
        if file and not isinstance(file, str):
            raise TypeError("Expected argument 'file' to be a str")
        pulumi.set(__self__, "file", file)
        if github and not isinstance(github, dict):
            raise TypeError("Expected argument 'github' to be a dict")
        pulumi.set(__self__, "github", github)
        if gitlab and not isinstance(gitlab, dict):
            raise TypeError("Expected argument 'gitlab' to be a dict")
        pulumi.set(__self__, "gitlab", gitlab)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)

    @_builtins.property
    @pulumi.getter
    def auth(self) -> Optional['outputs.GetPatchAuthResult']:
        """
        Authentication details used to call the GitHub or GitLab API when `github` or `gitlab` is set.
        """
        return pulumi.get(self, "auth")

    @_builtins.property
    @pulumi.getter
    def content(self) -> Optional[_builtins.str]:
        """
        Inline unified diff content.
        """
        return pulumi.get(self, "content")

    @_builtins.property
    @pulumi.getter
    def diff(self) -> _builtins.str:
        """
        Resolved unified diff content, from whichever of `content`, `file`, or `github` was set.
        """
        return pulumi.get(self, "diff")

    @_builtins.property
    @pulumi.getter
    def file(self) -> Optional[_builtins.str]:
        """
        Path to a local patch file, read on refresh.
        """
        return pulumi.get(self, "file")

    @_builtins.property
    @pulumi.getter
    def github(self) -> Optional['outputs.GetPatchGithubResult']:
        """
        Resolves the patch from a GitHub pull request or commit. Exactly one of `pr` or `commit` must be set.
        """
        return pulumi.get(self, "github")

    @_builtins.property
    @pulumi.getter
    def gitlab(self) -> Optional['outputs.GetPatchGitlabResult']:
        """
        Resolves the patch from a GitLab merge request or commit. Exactly one of `mr` or `commit` must be set.
        """
        return pulumi.get(self, "gitlab")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        Stable identifier for the patch: the hex-encoded sha256 of the resolved `diff`.
        """
        return pulumi.get(self, "id")


class AwaitableGetPatchResult(GetPatchResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetPatchResult(
            auth=self.auth,
            content=self.content,
            diff=self.diff,
            file=self.file,
            github=self.github,
            gitlab=self.gitlab,
            id=self.id)


def get_patch(auth: Optional[Union['GetPatchAuthArgs', 'GetPatchAuthArgsDict']] = None,
              content: Optional[_builtins.str] = None,
              file: Optional[_builtins.str] = None,
              github: Optional[Union['GetPatchGithubArgs', 'GetPatchGithubArgsDict']] = None,
              gitlab: Optional[Union['GetPatchGitlabArgs', 'GetPatchGitlabArgsDict']] = None,
              opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetPatchResult:
    """
    Resolves a single patch: a local file, inline diff content, or a remote host source (e.g. a GitHub PR/commit or a GitLab MR/commit). Exactly one of `content`, `file`, `github`, or `gitlab` must be set. Does not clone, apply, commit, or push; that is `Branch`'s responsibility.


    :param Union['GetPatchAuthArgs', 'GetPatchAuthArgsDict'] auth: Authentication details used to call the GitHub or GitLab API when `github` or `gitlab` is set.
    :param _builtins.str content: Inline unified diff content.
    :param _builtins.str file: Path to a local patch file, read on refresh.
    :param Union['GetPatchGithubArgs', 'GetPatchGithubArgsDict'] github: Resolves the patch from a GitHub pull request or commit. Exactly one of `pr` or `commit` must be set.
    :param Union['GetPatchGitlabArgs', 'GetPatchGitlabArgsDict'] gitlab: Resolves the patch from a GitLab merge request or commit. Exactly one of `mr` or `commit` must be set.
    """
    __args__ = dict()
    __args__['auth'] = auth
    __args__['content'] = content
    __args__['file'] = file
    __args__['github'] = github
    __args__['gitlab'] = gitlab
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('git:index/getPatch:getPatch', __args__, opts=opts, typ=GetPatchResult).value

    return AwaitableGetPatchResult(
        auth=pulumi.get(__ret__, 'auth'),
        content=pulumi.get(__ret__, 'content'),
        diff=pulumi.get(__ret__, 'diff'),
        file=pulumi.get(__ret__, 'file'),
        github=pulumi.get(__ret__, 'github'),
        gitlab=pulumi.get(__ret__, 'gitlab'),
        id=pulumi.get(__ret__, 'id'))
def get_patch_output(auth: pulumi.Input[Optional[Optional[Union['GetPatchAuthArgs', 'GetPatchAuthArgsDict']]]] = None,
                     content: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                     file: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                     github: pulumi.Input[Optional[Optional[Union['GetPatchGithubArgs', 'GetPatchGithubArgsDict']]]] = None,
                     gitlab: pulumi.Input[Optional[Optional[Union['GetPatchGitlabArgs', 'GetPatchGitlabArgsDict']]]] = None,
                     opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetPatchResult]:
    """
    Resolves a single patch: a local file, inline diff content, or a remote host source (e.g. a GitHub PR/commit or a GitLab MR/commit). Exactly one of `content`, `file`, `github`, or `gitlab` must be set. Does not clone, apply, commit, or push; that is `Branch`'s responsibility.


    :param Union['GetPatchAuthArgs', 'GetPatchAuthArgsDict'] auth: Authentication details used to call the GitHub or GitLab API when `github` or `gitlab` is set.
    :param _builtins.str content: Inline unified diff content.
    :param _builtins.str file: Path to a local patch file, read on refresh.
    :param Union['GetPatchGithubArgs', 'GetPatchGithubArgsDict'] github: Resolves the patch from a GitHub pull request or commit. Exactly one of `pr` or `commit` must be set.
    :param Union['GetPatchGitlabArgs', 'GetPatchGitlabArgsDict'] gitlab: Resolves the patch from a GitLab merge request or commit. Exactly one of `mr` or `commit` must be set.
    """
    __args__ = dict()
    __args__['auth'] = auth
    __args__['content'] = content
    __args__['file'] = file
    __args__['github'] = github
    __args__['gitlab'] = gitlab
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('git:index/getPatch:getPatch', __args__, opts=opts, typ=GetPatchResult)
    return __ret__.apply(lambda __response__: GetPatchResult(
        auth=pulumi.get(__response__, 'auth'),
        content=pulumi.get(__response__, 'content'),
        diff=pulumi.get(__response__, 'diff'),
        file=pulumi.get(__response__, 'file'),
        github=pulumi.get(__response__, 'github'),
        gitlab=pulumi.get(__response__, 'gitlab'),
        id=pulumi.get(__response__, 'id')))
