# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'BranchRepository',
    'BranchRepositoryAuth',
    'GetPatchAuthResult',
    'GetPatchGithubResult',
    'GetPatchGitlabResult',
    'GetRepositoryAuthResult',
]

@pulumi.output_type
class BranchRepository(dict):
    def __init__(__self__, *,
                 url: _builtins.str,
                 auth: Optional['outputs.BranchRepositoryAuth'] = None,
                 host: Optional[_builtins.str] = None):
        """
        :param _builtins.str url: URL of the repository.
        :param 'BranchRepositoryAuthArgs' auth: Authentication details used to connect to the repository.
        :param _builtins.str host: Type of host the repository is on. Must be one of `github`, `gitlab`, or `generic`.
        """
        pulumi.set(__self__, "url", url)
        if auth is not None:
            pulumi.set(__self__, "auth", auth)
        if host is not None:
            pulumi.set(__self__, "host", host)

    @_builtins.property
    @pulumi.getter
    def url(self) -> _builtins.str:
        """
        URL of the repository.
        """
        return pulumi.get(self, "url")

    @_builtins.property
    @pulumi.getter
    def auth(self) -> Optional['outputs.BranchRepositoryAuth']:
        """
        Authentication details used to connect to the repository.
        """
        return pulumi.get(self, "auth")

    @_builtins.property
    @pulumi.getter
    def host(self) -> Optional[_builtins.str]:
        """
        Type of host the repository is on. Must be one of `github`, `gitlab`, or `generic`.
        """
        return pulumi.get(self, "host")


@pulumi.output_type
class BranchRepositoryAuth(dict):
    def __init__(__self__, *,
                 token: Optional[_builtins.str] = None):
        """
        :param _builtins.str token: Token used to authenticate with the repository host.
        """
        if token is not None:
            pulumi.set(__self__, "token", token)

    @_builtins.property
    @pulumi.getter
    def token(self) -> Optional[_builtins.str]:
        """
        Token used to authenticate with the repository host.
        """
        return pulumi.get(self, "token")


@pulumi.output_type
class GetPatchAuthResult(dict):
    def __init__(__self__, *,
                 token: Optional[_builtins.str] = None):
        """
        :param _builtins.str token: Token used to authenticate with the GitHub or GitLab API.
        """
        if token is not None:
            pulumi.set(__self__, "token", token)

    @_builtins.property
    @pulumi.getter
    def token(self) -> Optional[_builtins.str]:
        """
        Token used to authenticate with the GitHub or GitLab API.
        """
        return pulumi.get(self, "token")


@pulumi.output_type
class GetPatchGithubResult(dict):
    def __init__(__self__, *,
                 repository: _builtins.str,
                 sha: _builtins.str,
                 commit: Optional[_builtins.str] = None,
                 pr: Optional[_builtins.int] = None):
        """
        :param _builtins.str repository: Repository the pull request or commit belongs to, in `owner/name` form.
        :param _builtins.str sha: Resolved commit sha (the pull request's head commit, or `commit` itself).
        :param _builtins.str commit: Commit sha to resolve the patch from.
        :param _builtins.int pr: Pull request number to resolve the patch from.
        """
        pulumi.set(__self__, "repository", repository)
        pulumi.set(__self__, "sha", sha)
        if commit is not None:
            pulumi.set(__self__, "commit", commit)
        if pr is not None:
            pulumi.set(__self__, "pr", pr)

    @_builtins.property
    @pulumi.getter
    def repository(self) -> _builtins.str:
        """
        Repository the pull request or commit belongs to, in `owner/name` form.
        """
        return pulumi.get(self, "repository")

    @_builtins.property
    @pulumi.getter
    def sha(self) -> _builtins.str:
        """
        Resolved commit sha (the pull request's head commit, or `commit` itself).
        """
        return pulumi.get(self, "sha")

    @_builtins.property
    @pulumi.getter
    def commit(self) -> Optional[_builtins.str]:
        """
        Commit sha to resolve the patch from.
        """
        return pulumi.get(self, "commit")

    @_builtins.property
    @pulumi.getter
    def pr(self) -> Optional[_builtins.int]:
        """
        Pull request number to resolve the patch from.
        """
        return pulumi.get(self, "pr")


@pulumi.output_type
class GetPatchGitlabResult(dict):
    def __init__(__self__, *,
                 project: _builtins.str,
                 sha: _builtins.str,
                 commit: Optional[_builtins.str] = None,
                 mr: Optional[_builtins.int] = None):
        """
        :param _builtins.str project: Project the merge request or commit belongs to, as a GitLab project path (e.g. `group/project`) or numeric ID.
        :param _builtins.str sha: Resolved commit sha (the merge request's head commit, or `commit` itself).
        :param _builtins.str commit: Commit sha to resolve the patch from.
        :param _builtins.int mr: Merge request IID to resolve the patch from.
        """
        pulumi.set(__self__, "project", project)
        pulumi.set(__self__, "sha", sha)
        if commit is not None:
            pulumi.set(__self__, "commit", commit)
        if mr is not None:
            pulumi.set(__self__, "mr", mr)

    @_builtins.property
    @pulumi.getter
    def project(self) -> _builtins.str:
        """
        Project the merge request or commit belongs to, as a GitLab project path (e.g. `group/project`) or numeric ID.
        """
        return pulumi.get(self, "project")

    @_builtins.property
    @pulumi.getter
    def sha(self) -> _builtins.str:
        """
        Resolved commit sha (the merge request's head commit, or `commit` itself).
        """
        return pulumi.get(self, "sha")

    @_builtins.property
    @pulumi.getter
    def commit(self) -> Optional[_builtins.str]:
        """
        Commit sha to resolve the patch from.
        """
        return pulumi.get(self, "commit")

    @_builtins.property
    @pulumi.getter
    def mr(self) -> Optional[_builtins.int]:
        """
        Merge request IID to resolve the patch from.
        """
        return pulumi.get(self, "mr")


@pulumi.output_type
class GetRepositoryAuthResult(dict):
    def __init__(__self__, *,
                 token: Optional[_builtins.str] = None):
        """
        :param _builtins.str token: Token used to authenticate with the repository host.
        """
        if token is not None:
            pulumi.set(__self__, "token", token)

    @_builtins.property
    @pulumi.getter
    def token(self) -> Optional[_builtins.str]:
        """
        Token used to authenticate with the repository host.
        """
        return pulumi.get(self, "token")


