// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Git.Inputs
{

    public sealed class BranchRepositoryArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Authentication details used to connect to the repository.
        /// </summary>
        [Input("auth")]
        public Input<Inputs.BranchRepositoryAuthArgs>? Auth { get; set; }

        /// <summary>
        /// Type of host the repository is on. Must be one of `Github`, `Gitlab`, or `Generic`.
        /// </summary>
        [Input("host")]
        public Input<string>? Host { get; set; }

        /// <summary>
        /// URL of the repository.
        /// </summary>
        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        public BranchRepositoryArgs()
        {
        }
        public static new BranchRepositoryArgs Empty => new BranchRepositoryArgs();
    }
}
