// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Git.Inputs
{

    public sealed class GetPatchAuthArgs : global::Pulumi.InvokeArgs
    {
        [Input("token")]
        private string? _token;

        /// <summary>
        /// Token used to authenticate with the GitHub or GitLab API.
        /// </summary>
        public string? Token
        {
            get => _token;
            set => _token = value;
        }

        public GetPatchAuthArgs()
        {
        }
        public static new GetPatchAuthArgs Empty => new GetPatchAuthArgs();
    }
}
