// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Git.Inputs
{

    public sealed class GetPatchAuthInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("token")]
        private Input<string>? _token;

        /// <summary>
        /// Token used to authenticate with the GitHub or GitLab API.
        /// </summary>
        public Input<string>? Token
        {
            get => _token;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _token = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public GetPatchAuthInputArgs()
        {
        }
        public static new GetPatchAuthInputArgs Empty => new GetPatchAuthInputArgs();
    }
}
