// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Git.Inputs
{

    public sealed class GetPatchGithubArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Commit sha to resolve the patch from.
        /// </summary>
        [Input("commit")]
        public string? Commit { get; set; }

        /// <summary>
        /// Pull request number to resolve the patch from.
        /// </summary>
        [Input("pr")]
        public int? Pr { get; set; }

        /// <summary>
        /// Repository the pull request or commit belongs to, in `owner/name` form.
        /// </summary>
        [Input("repository", required: true)]
        public string Repository { get; set; } = null!;

        /// <summary>
        /// Resolved commit sha (the pull request's head commit, or `Commit` itself).
        /// </summary>
        [Input("sha", required: true)]
        public string Sha { get; set; } = null!;

        public GetPatchGithubArgs()
        {
        }
        public static new GetPatchGithubArgs Empty => new GetPatchGithubArgs();
    }
}
