// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Git.Inputs
{

    public sealed class GetPatchGitlabInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Commit sha to resolve the patch from.
        /// </summary>
        [Input("commit")]
        public Input<string>? Commit { get; set; }

        /// <summary>
        /// Merge request IID to resolve the patch from.
        /// </summary>
        [Input("mr")]
        public Input<int>? Mr { get; set; }

        /// <summary>
        /// Project the merge request or commit belongs to, as a GitLab project path (e.g. `group/project`) or numeric ID.
        /// </summary>
        [Input("project", required: true)]
        public Input<string> Project { get; set; } = null!;

        /// <summary>
        /// Resolved commit sha (the merge request's head commit, or `Commit` itself).
        /// </summary>
        [Input("sha", required: true)]
        public Input<string> Sha { get; set; } = null!;

        public GetPatchGitlabInputArgs()
        {
        }
        public static new GetPatchGitlabInputArgs Empty => new GetPatchGitlabInputArgs();
    }
}
