// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package git

import (
	"context"
	"reflect"

	"errors"
	"github.com/UnstoppableMango/pulumi-provider-git/sdk/go/git/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Tracks a branch's base ref within a repository, and optionally an ordered patch stack applied on top of it. When `patches` is set, the resulting commits are force-pushed to the branch on the remote; otherwise this resource only resolves and tracks the observed base ref.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/UnstoppableMango/pulumi-provider-git/sdk/go/git"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Omits the required_providers block since this example also runs as an
//			// acceptance test against an in-process build; see examples/provider/provider.tf.
//			// Tracks the "main" branch of a public repository. Safe to run against a
//			// repository you don't own; git_branch never pushes.
//			main, err := git.NewBranch(ctx, "main", &git.BranchArgs{
//				Repository: &git.BranchRepositoryArgs{
//					Url:  pulumi.String("https://github.com/UnstoppableMango/terraform-provider-git.git"),
//					Host: pulumi.String("github"),
//				},
//				Name:    pulumi.String("main"),
//				BaseRef: pulumi.String("main"),
//			})
//			if err != nil {
//				return err
//			}
//			ctx.Export("resolvedSha", main.BaseSha)
//			return nil
//		})
//	}
//
// ```
type Branch struct {
	pulumi.CustomResourceState

	// Ref this branch is based on.
	BaseRef pulumi.StringOutput `pulumi:"baseRef"`
	// Resolved commit hash of `baseRef` as of the last read.
	BaseSha pulumi.StringOutput `pulumi:"baseSha"`
	// Name of the branch.
	Name pulumi.StringOutput `pulumi:"name"`
	// How to handle the branch's remote tip having moved since it was last observed, when pushing the patch stack. `force` (default) always force-pushes, discarding drift, matching this provider's historical behavior. `fail` aborts the push instead of clobbering unexpected remote changes; re-run `pulumi up` to pick up the new tip, or resolve the drift manually. Only takes effect when `patches` is set. Must be one of `fail` or `force`.
	OnConflict pulumi.StringOutput `pulumi:"onConflict"`
	// Ordered list of patch diffs applied on top of base_ref, in the spirit of quilt push. When set, the resulting commits are force-pushed to the branch on the remote.
	Patches pulumi.StringArrayOutput `pulumi:"patches"`
	// Repository the branch belongs to.
	Repository BranchRepositoryOutput `pulumi:"repository"`
	// Resolved commit hash the branch currently tracks.
	ResolvedRef pulumi.StringOutput `pulumi:"resolvedRef"`
}

// NewBranch registers a new resource with the given unique name, arguments, and options.
func NewBranch(ctx *pulumi.Context,
	name string, args *BranchArgs, opts ...pulumi.ResourceOption) (*Branch, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.BaseRef == nil {
		return nil, errors.New("invalid value for required argument 'BaseRef'")
	}
	if args.Repository == nil {
		return nil, errors.New("invalid value for required argument 'Repository'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Branch
	err := ctx.RegisterResource("git:index/branch:Branch", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetBranch gets an existing Branch resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetBranch(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *BranchState, opts ...pulumi.ResourceOption) (*Branch, error) {
	var resource Branch
	err := ctx.ReadResource("git:index/branch:Branch", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Branch resources.
type branchState struct {
	// Ref this branch is based on.
	BaseRef *string `pulumi:"baseRef"`
	// Resolved commit hash of `baseRef` as of the last read.
	BaseSha *string `pulumi:"baseSha"`
	// Name of the branch.
	Name *string `pulumi:"name"`
	// How to handle the branch's remote tip having moved since it was last observed, when pushing the patch stack. `force` (default) always force-pushes, discarding drift, matching this provider's historical behavior. `fail` aborts the push instead of clobbering unexpected remote changes; re-run `pulumi up` to pick up the new tip, or resolve the drift manually. Only takes effect when `patches` is set. Must be one of `fail` or `force`.
	OnConflict *string `pulumi:"onConflict"`
	// Ordered list of patch diffs applied on top of base_ref, in the spirit of quilt push. When set, the resulting commits are force-pushed to the branch on the remote.
	Patches []string `pulumi:"patches"`
	// Repository the branch belongs to.
	Repository *BranchRepository `pulumi:"repository"`
	// Resolved commit hash the branch currently tracks.
	ResolvedRef *string `pulumi:"resolvedRef"`
}

type BranchState struct {
	// Ref this branch is based on.
	BaseRef pulumi.StringPtrInput
	// Resolved commit hash of `baseRef` as of the last read.
	BaseSha pulumi.StringPtrInput
	// Name of the branch.
	Name pulumi.StringPtrInput
	// How to handle the branch's remote tip having moved since it was last observed, when pushing the patch stack. `force` (default) always force-pushes, discarding drift, matching this provider's historical behavior. `fail` aborts the push instead of clobbering unexpected remote changes; re-run `pulumi up` to pick up the new tip, or resolve the drift manually. Only takes effect when `patches` is set. Must be one of `fail` or `force`.
	OnConflict pulumi.StringPtrInput
	// Ordered list of patch diffs applied on top of base_ref, in the spirit of quilt push. When set, the resulting commits are force-pushed to the branch on the remote.
	Patches pulumi.StringArrayInput
	// Repository the branch belongs to.
	Repository BranchRepositoryPtrInput
	// Resolved commit hash the branch currently tracks.
	ResolvedRef pulumi.StringPtrInput
}

func (BranchState) ElementType() reflect.Type {
	return reflect.TypeOf((*branchState)(nil)).Elem()
}

type branchArgs struct {
	// Ref this branch is based on.
	BaseRef string `pulumi:"baseRef"`
	// Name of the branch.
	Name *string `pulumi:"name"`
	// How to handle the branch's remote tip having moved since it was last observed, when pushing the patch stack. `force` (default) always force-pushes, discarding drift, matching this provider's historical behavior. `fail` aborts the push instead of clobbering unexpected remote changes; re-run `pulumi up` to pick up the new tip, or resolve the drift manually. Only takes effect when `patches` is set. Must be one of `fail` or `force`.
	OnConflict *string `pulumi:"onConflict"`
	// Ordered list of patch diffs applied on top of base_ref, in the spirit of quilt push. When set, the resulting commits are force-pushed to the branch on the remote.
	Patches []string `pulumi:"patches"`
	// Repository the branch belongs to.
	Repository BranchRepository `pulumi:"repository"`
}

// The set of arguments for constructing a Branch resource.
type BranchArgs struct {
	// Ref this branch is based on.
	BaseRef pulumi.StringInput
	// Name of the branch.
	Name pulumi.StringPtrInput
	// How to handle the branch's remote tip having moved since it was last observed, when pushing the patch stack. `force` (default) always force-pushes, discarding drift, matching this provider's historical behavior. `fail` aborts the push instead of clobbering unexpected remote changes; re-run `pulumi up` to pick up the new tip, or resolve the drift manually. Only takes effect when `patches` is set. Must be one of `fail` or `force`.
	OnConflict pulumi.StringPtrInput
	// Ordered list of patch diffs applied on top of base_ref, in the spirit of quilt push. When set, the resulting commits are force-pushed to the branch on the remote.
	Patches pulumi.StringArrayInput
	// Repository the branch belongs to.
	Repository BranchRepositoryInput
}

func (BranchArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*branchArgs)(nil)).Elem()
}

type BranchInput interface {
	pulumi.Input

	ToBranchOutput() BranchOutput
	ToBranchOutputWithContext(ctx context.Context) BranchOutput
}

func (*Branch) ElementType() reflect.Type {
	return reflect.TypeOf((**Branch)(nil)).Elem()
}

func (i *Branch) ToBranchOutput() BranchOutput {
	return i.ToBranchOutputWithContext(context.Background())
}

func (i *Branch) ToBranchOutputWithContext(ctx context.Context) BranchOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BranchOutput)
}

// BranchArrayInput is an input type that accepts BranchArray and BranchArrayOutput values.
// You can construct a concrete instance of `BranchArrayInput` via:
//
//	BranchArray{ BranchArgs{...} }
type BranchArrayInput interface {
	pulumi.Input

	ToBranchArrayOutput() BranchArrayOutput
	ToBranchArrayOutputWithContext(context.Context) BranchArrayOutput
}

type BranchArray []BranchInput

func (BranchArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Branch)(nil)).Elem()
}

func (i BranchArray) ToBranchArrayOutput() BranchArrayOutput {
	return i.ToBranchArrayOutputWithContext(context.Background())
}

func (i BranchArray) ToBranchArrayOutputWithContext(ctx context.Context) BranchArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BranchArrayOutput)
}

// BranchMapInput is an input type that accepts BranchMap and BranchMapOutput values.
// You can construct a concrete instance of `BranchMapInput` via:
//
//	BranchMap{ "key": BranchArgs{...} }
type BranchMapInput interface {
	pulumi.Input

	ToBranchMapOutput() BranchMapOutput
	ToBranchMapOutputWithContext(context.Context) BranchMapOutput
}

type BranchMap map[string]BranchInput

func (BranchMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Branch)(nil)).Elem()
}

func (i BranchMap) ToBranchMapOutput() BranchMapOutput {
	return i.ToBranchMapOutputWithContext(context.Background())
}

func (i BranchMap) ToBranchMapOutputWithContext(ctx context.Context) BranchMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BranchMapOutput)
}

type BranchOutput struct{ *pulumi.OutputState }

func (BranchOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Branch)(nil)).Elem()
}

func (o BranchOutput) ToBranchOutput() BranchOutput {
	return o
}

func (o BranchOutput) ToBranchOutputWithContext(ctx context.Context) BranchOutput {
	return o
}

// Ref this branch is based on.
func (o BranchOutput) BaseRef() pulumi.StringOutput {
	return o.ApplyT(func(v *Branch) pulumi.StringOutput { return v.BaseRef }).(pulumi.StringOutput)
}

// Resolved commit hash of `baseRef` as of the last read.
func (o BranchOutput) BaseSha() pulumi.StringOutput {
	return o.ApplyT(func(v *Branch) pulumi.StringOutput { return v.BaseSha }).(pulumi.StringOutput)
}

// Name of the branch.
func (o BranchOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Branch) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// How to handle the branch's remote tip having moved since it was last observed, when pushing the patch stack. `force` (default) always force-pushes, discarding drift, matching this provider's historical behavior. `fail` aborts the push instead of clobbering unexpected remote changes; re-run `pulumi up` to pick up the new tip, or resolve the drift manually. Only takes effect when `patches` is set. Must be one of `fail` or `force`.
func (o BranchOutput) OnConflict() pulumi.StringOutput {
	return o.ApplyT(func(v *Branch) pulumi.StringOutput { return v.OnConflict }).(pulumi.StringOutput)
}

// Ordered list of patch diffs applied on top of base_ref, in the spirit of quilt push. When set, the resulting commits are force-pushed to the branch on the remote.
func (o BranchOutput) Patches() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Branch) pulumi.StringArrayOutput { return v.Patches }).(pulumi.StringArrayOutput)
}

// Repository the branch belongs to.
func (o BranchOutput) Repository() BranchRepositoryOutput {
	return o.ApplyT(func(v *Branch) BranchRepositoryOutput { return v.Repository }).(BranchRepositoryOutput)
}

// Resolved commit hash the branch currently tracks.
func (o BranchOutput) ResolvedRef() pulumi.StringOutput {
	return o.ApplyT(func(v *Branch) pulumi.StringOutput { return v.ResolvedRef }).(pulumi.StringOutput)
}

type BranchArrayOutput struct{ *pulumi.OutputState }

func (BranchArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Branch)(nil)).Elem()
}

func (o BranchArrayOutput) ToBranchArrayOutput() BranchArrayOutput {
	return o
}

func (o BranchArrayOutput) ToBranchArrayOutputWithContext(ctx context.Context) BranchArrayOutput {
	return o
}

func (o BranchArrayOutput) Index(i pulumi.IntInput) BranchOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Branch {
		return vs[0].([]*Branch)[vs[1].(int)]
	}).(BranchOutput)
}

type BranchMapOutput struct{ *pulumi.OutputState }

func (BranchMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Branch)(nil)).Elem()
}

func (o BranchMapOutput) ToBranchMapOutput() BranchMapOutput {
	return o
}

func (o BranchMapOutput) ToBranchMapOutputWithContext(ctx context.Context) BranchMapOutput {
	return o
}

func (o BranchMapOutput) MapIndex(k pulumi.StringInput) BranchOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Branch {
		return vs[0].(map[string]*Branch)[vs[1].(string)]
	}).(BranchOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*BranchInput)(nil)).Elem(), &Branch{})
	pulumi.RegisterInputType(reflect.TypeOf((*BranchArrayInput)(nil)).Elem(), BranchArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*BranchMapInput)(nil)).Elem(), BranchMap{})
	pulumi.RegisterOutputType(BranchOutput{})
	pulumi.RegisterOutputType(BranchArrayOutput{})
	pulumi.RegisterOutputType(BranchMapOutput{})
}
