// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package git

import (
	"context"
	"reflect"

	"github.com/UnstoppableMango/pulumi-provider-git/sdk/go/git/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Resolves a single patch: a local file, inline diff content, or a remote host source (e.g. a GitHub PR/commit or a GitLab MR/commit). Exactly one of `content`, `file`, `github`, or `gitlab` must be set. Does not clone, apply, commit, or push; that is `Branch`'s responsibility.
func GetPatch(ctx *pulumi.Context, args *GetPatchArgs, opts ...pulumi.InvokeOption) (*GetPatchResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetPatchResult
	err := ctx.Invoke("git:index/getPatch:getPatch", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPatch.
type GetPatchArgs struct {
	// Authentication details used to call the GitHub or GitLab API when `github` or `gitlab` is set.
	Auth *GetPatchAuth `pulumi:"auth"`
	// Inline unified diff content.
	Content *string `pulumi:"content"`
	// Path to a local patch file, read on refresh.
	File *string `pulumi:"file"`
	// Resolves the patch from a GitHub pull request or commit. Exactly one of `pr` or `commit` must be set.
	Github *GetPatchGithub `pulumi:"github"`
	// Resolves the patch from a GitLab merge request or commit. Exactly one of `mr` or `commit` must be set.
	Gitlab *GetPatchGitlab `pulumi:"gitlab"`
}

// A collection of values returned by getPatch.
type GetPatchResult struct {
	// Authentication details used to call the GitHub or GitLab API when `github` or `gitlab` is set.
	Auth *GetPatchAuth `pulumi:"auth"`
	// Inline unified diff content.
	Content *string `pulumi:"content"`
	// Resolved unified diff content, from whichever of `content`, `file`, or `github` was set.
	Diff string `pulumi:"diff"`
	// Path to a local patch file, read on refresh.
	File *string `pulumi:"file"`
	// Resolves the patch from a GitHub pull request or commit. Exactly one of `pr` or `commit` must be set.
	Github *GetPatchGithub `pulumi:"github"`
	// Resolves the patch from a GitLab merge request or commit. Exactly one of `mr` or `commit` must be set.
	Gitlab *GetPatchGitlab `pulumi:"gitlab"`
	// Stable identifier for the patch: the hex-encoded sha256 of the resolved `diff`.
	Id string `pulumi:"id"`
}

func GetPatchOutput(ctx *pulumi.Context, args GetPatchOutputArgs, opts ...pulumi.InvokeOption) GetPatchResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetPatchResultOutput, error) {
			args := v.(GetPatchArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("git:index/getPatch:getPatch", args, GetPatchResultOutput{}, options).(GetPatchResultOutput), nil
		}).(GetPatchResultOutput)
}

// A collection of arguments for invoking getPatch.
type GetPatchOutputArgs struct {
	// Authentication details used to call the GitHub or GitLab API when `github` or `gitlab` is set.
	Auth GetPatchAuthPtrInput `pulumi:"auth"`
	// Inline unified diff content.
	Content pulumi.StringPtrInput `pulumi:"content"`
	// Path to a local patch file, read on refresh.
	File pulumi.StringPtrInput `pulumi:"file"`
	// Resolves the patch from a GitHub pull request or commit. Exactly one of `pr` or `commit` must be set.
	Github GetPatchGithubPtrInput `pulumi:"github"`
	// Resolves the patch from a GitLab merge request or commit. Exactly one of `mr` or `commit` must be set.
	Gitlab GetPatchGitlabPtrInput `pulumi:"gitlab"`
}

func (GetPatchOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPatchArgs)(nil)).Elem()
}

// A collection of values returned by getPatch.
type GetPatchResultOutput struct{ *pulumi.OutputState }

func (GetPatchResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPatchResult)(nil)).Elem()
}

func (o GetPatchResultOutput) ToGetPatchResultOutput() GetPatchResultOutput {
	return o
}

func (o GetPatchResultOutput) ToGetPatchResultOutputWithContext(ctx context.Context) GetPatchResultOutput {
	return o
}

// Authentication details used to call the GitHub or GitLab API when `github` or `gitlab` is set.
func (o GetPatchResultOutput) Auth() GetPatchAuthPtrOutput {
	return o.ApplyT(func(v GetPatchResult) *GetPatchAuth { return v.Auth }).(GetPatchAuthPtrOutput)
}

// Inline unified diff content.
func (o GetPatchResultOutput) Content() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetPatchResult) *string { return v.Content }).(pulumi.StringPtrOutput)
}

// Resolved unified diff content, from whichever of `content`, `file`, or `github` was set.
func (o GetPatchResultOutput) Diff() pulumi.StringOutput {
	return o.ApplyT(func(v GetPatchResult) string { return v.Diff }).(pulumi.StringOutput)
}

// Path to a local patch file, read on refresh.
func (o GetPatchResultOutput) File() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetPatchResult) *string { return v.File }).(pulumi.StringPtrOutput)
}

// Resolves the patch from a GitHub pull request or commit. Exactly one of `pr` or `commit` must be set.
func (o GetPatchResultOutput) Github() GetPatchGithubPtrOutput {
	return o.ApplyT(func(v GetPatchResult) *GetPatchGithub { return v.Github }).(GetPatchGithubPtrOutput)
}

// Resolves the patch from a GitLab merge request or commit. Exactly one of `mr` or `commit` must be set.
func (o GetPatchResultOutput) Gitlab() GetPatchGitlabPtrOutput {
	return o.ApplyT(func(v GetPatchResult) *GetPatchGitlab { return v.Gitlab }).(GetPatchGitlabPtrOutput)
}

// Stable identifier for the patch: the hex-encoded sha256 of the resolved `diff`.
func (o GetPatchResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetPatchResult) string { return v.Id }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetPatchResultOutput{})
}
