// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package git

import (
	"context"
	"reflect"

	"github.com/UnstoppableMango/pulumi-provider-git/sdk/go/git/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// References an existing repository. Reference-only: this provider never creates or deletes repositories on the host. It resolves connection details (URL, host type, auth) used by other resources.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/UnstoppableMango/pulumi-provider-git/sdk/go/git"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Omits the required_providers block since this example also runs as an
//			// acceptance test against an in-process build; see examples/provider/provider.tf.
//			// Resolves and verifies a public repository via ls-remote.
//			this, err := git.GetRepository(ctx, &git.GetRepositoryArgs{
//				Url:  "https://github.com/UnstoppableMango/terraform-provider-git.git",
//				Host: pulumi.StringRef("github"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("repositoryId", this.Id)
//			return nil
//		})
//	}
//
// ```
func GetRepository(ctx *pulumi.Context, args *GetRepositoryArgs, opts ...pulumi.InvokeOption) (*GetRepositoryResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetRepositoryResult
	err := ctx.Invoke("git:index/getRepository:getRepository", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getRepository.
type GetRepositoryArgs struct {
	// Authentication details used to connect to the repository.
	Auth *GetRepositoryAuth `pulumi:"auth"`
	// Type of host the repository is on. Must be one of `github`, `gitlab`, or `generic`.
	Host *string `pulumi:"host"`
	// URL of the repository.
	Url string `pulumi:"url"`
}

// A collection of values returned by getRepository.
type GetRepositoryResult struct {
	// Authentication details used to connect to the repository.
	Auth *GetRepositoryAuth `pulumi:"auth"`
	// Type of host the repository is on. Must be one of `github`, `gitlab`, or `generic`.
	Host *string `pulumi:"host"`
	// Identifier for the repository. Mirrors the `url` attribute.
	Id string `pulumi:"id"`
	// URL of the repository.
	Url string `pulumi:"url"`
}

func GetRepositoryOutput(ctx *pulumi.Context, args GetRepositoryOutputArgs, opts ...pulumi.InvokeOption) GetRepositoryResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetRepositoryResultOutput, error) {
			args := v.(GetRepositoryArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("git:index/getRepository:getRepository", args, GetRepositoryResultOutput{}, options).(GetRepositoryResultOutput), nil
		}).(GetRepositoryResultOutput)
}

// A collection of arguments for invoking getRepository.
type GetRepositoryOutputArgs struct {
	// Authentication details used to connect to the repository.
	Auth GetRepositoryAuthPtrInput `pulumi:"auth"`
	// Type of host the repository is on. Must be one of `github`, `gitlab`, or `generic`.
	Host pulumi.StringPtrInput `pulumi:"host"`
	// URL of the repository.
	Url pulumi.StringInput `pulumi:"url"`
}

func (GetRepositoryOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetRepositoryArgs)(nil)).Elem()
}

// A collection of values returned by getRepository.
type GetRepositoryResultOutput struct{ *pulumi.OutputState }

func (GetRepositoryResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetRepositoryResult)(nil)).Elem()
}

func (o GetRepositoryResultOutput) ToGetRepositoryResultOutput() GetRepositoryResultOutput {
	return o
}

func (o GetRepositoryResultOutput) ToGetRepositoryResultOutputWithContext(ctx context.Context) GetRepositoryResultOutput {
	return o
}

// Authentication details used to connect to the repository.
func (o GetRepositoryResultOutput) Auth() GetRepositoryAuthPtrOutput {
	return o.ApplyT(func(v GetRepositoryResult) *GetRepositoryAuth { return v.Auth }).(GetRepositoryAuthPtrOutput)
}

// Type of host the repository is on. Must be one of `github`, `gitlab`, or `generic`.
func (o GetRepositoryResultOutput) Host() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetRepositoryResult) *string { return v.Host }).(pulumi.StringPtrOutput)
}

// Identifier for the repository. Mirrors the `url` attribute.
func (o GetRepositoryResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetRepositoryResult) string { return v.Id }).(pulumi.StringOutput)
}

// URL of the repository.
func (o GetRepositoryResultOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v GetRepositoryResult) string { return v.Url }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetRepositoryResultOutput{})
}
