// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package git

import (
	"context"
	"reflect"

	"github.com/UnstoppableMango/pulumi-provider-git/sdk/go/git/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type BranchRepository struct {
	// Authentication details used to connect to the repository.
	Auth *BranchRepositoryAuth `pulumi:"auth"`
	// Type of host the repository is on. Must be one of `github`, `gitlab`, or `generic`.
	Host *string `pulumi:"host"`
	// URL of the repository.
	Url string `pulumi:"url"`
}

// BranchRepositoryInput is an input type that accepts BranchRepositoryArgs and BranchRepositoryOutput values.
// You can construct a concrete instance of `BranchRepositoryInput` via:
//
//	BranchRepositoryArgs{...}
type BranchRepositoryInput interface {
	pulumi.Input

	ToBranchRepositoryOutput() BranchRepositoryOutput
	ToBranchRepositoryOutputWithContext(context.Context) BranchRepositoryOutput
}

type BranchRepositoryArgs struct {
	// Authentication details used to connect to the repository.
	Auth BranchRepositoryAuthPtrInput `pulumi:"auth"`
	// Type of host the repository is on. Must be one of `github`, `gitlab`, or `generic`.
	Host pulumi.StringPtrInput `pulumi:"host"`
	// URL of the repository.
	Url pulumi.StringInput `pulumi:"url"`
}

func (BranchRepositoryArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*BranchRepository)(nil)).Elem()
}

func (i BranchRepositoryArgs) ToBranchRepositoryOutput() BranchRepositoryOutput {
	return i.ToBranchRepositoryOutputWithContext(context.Background())
}

func (i BranchRepositoryArgs) ToBranchRepositoryOutputWithContext(ctx context.Context) BranchRepositoryOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BranchRepositoryOutput)
}

func (i BranchRepositoryArgs) ToBranchRepositoryPtrOutput() BranchRepositoryPtrOutput {
	return i.ToBranchRepositoryPtrOutputWithContext(context.Background())
}

func (i BranchRepositoryArgs) ToBranchRepositoryPtrOutputWithContext(ctx context.Context) BranchRepositoryPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BranchRepositoryOutput).ToBranchRepositoryPtrOutputWithContext(ctx)
}

// BranchRepositoryPtrInput is an input type that accepts BranchRepositoryArgs, BranchRepositoryPtr and BranchRepositoryPtrOutput values.
// You can construct a concrete instance of `BranchRepositoryPtrInput` via:
//
//	        BranchRepositoryArgs{...}
//
//	or:
//
//	        nil
type BranchRepositoryPtrInput interface {
	pulumi.Input

	ToBranchRepositoryPtrOutput() BranchRepositoryPtrOutput
	ToBranchRepositoryPtrOutputWithContext(context.Context) BranchRepositoryPtrOutput
}

type branchRepositoryPtrType BranchRepositoryArgs

func BranchRepositoryPtr(v *BranchRepositoryArgs) BranchRepositoryPtrInput {
	return (*branchRepositoryPtrType)(v)
}

func (*branchRepositoryPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**BranchRepository)(nil)).Elem()
}

func (i *branchRepositoryPtrType) ToBranchRepositoryPtrOutput() BranchRepositoryPtrOutput {
	return i.ToBranchRepositoryPtrOutputWithContext(context.Background())
}

func (i *branchRepositoryPtrType) ToBranchRepositoryPtrOutputWithContext(ctx context.Context) BranchRepositoryPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BranchRepositoryPtrOutput)
}

type BranchRepositoryOutput struct{ *pulumi.OutputState }

func (BranchRepositoryOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*BranchRepository)(nil)).Elem()
}

func (o BranchRepositoryOutput) ToBranchRepositoryOutput() BranchRepositoryOutput {
	return o
}

func (o BranchRepositoryOutput) ToBranchRepositoryOutputWithContext(ctx context.Context) BranchRepositoryOutput {
	return o
}

func (o BranchRepositoryOutput) ToBranchRepositoryPtrOutput() BranchRepositoryPtrOutput {
	return o.ToBranchRepositoryPtrOutputWithContext(context.Background())
}

func (o BranchRepositoryOutput) ToBranchRepositoryPtrOutputWithContext(ctx context.Context) BranchRepositoryPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v BranchRepository) *BranchRepository {
		return &v
	}).(BranchRepositoryPtrOutput)
}

// Authentication details used to connect to the repository.
func (o BranchRepositoryOutput) Auth() BranchRepositoryAuthPtrOutput {
	return o.ApplyT(func(v BranchRepository) *BranchRepositoryAuth { return v.Auth }).(BranchRepositoryAuthPtrOutput)
}

// Type of host the repository is on. Must be one of `github`, `gitlab`, or `generic`.
func (o BranchRepositoryOutput) Host() pulumi.StringPtrOutput {
	return o.ApplyT(func(v BranchRepository) *string { return v.Host }).(pulumi.StringPtrOutput)
}

// URL of the repository.
func (o BranchRepositoryOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v BranchRepository) string { return v.Url }).(pulumi.StringOutput)
}

type BranchRepositoryPtrOutput struct{ *pulumi.OutputState }

func (BranchRepositoryPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**BranchRepository)(nil)).Elem()
}

func (o BranchRepositoryPtrOutput) ToBranchRepositoryPtrOutput() BranchRepositoryPtrOutput {
	return o
}

func (o BranchRepositoryPtrOutput) ToBranchRepositoryPtrOutputWithContext(ctx context.Context) BranchRepositoryPtrOutput {
	return o
}

func (o BranchRepositoryPtrOutput) Elem() BranchRepositoryOutput {
	return o.ApplyT(func(v *BranchRepository) BranchRepository {
		if v != nil {
			return *v
		}
		var ret BranchRepository
		return ret
	}).(BranchRepositoryOutput)
}

// Authentication details used to connect to the repository.
func (o BranchRepositoryPtrOutput) Auth() BranchRepositoryAuthPtrOutput {
	return o.ApplyT(func(v *BranchRepository) *BranchRepositoryAuth {
		if v == nil {
			return nil
		}
		return v.Auth
	}).(BranchRepositoryAuthPtrOutput)
}

// Type of host the repository is on. Must be one of `github`, `gitlab`, or `generic`.
func (o BranchRepositoryPtrOutput) Host() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *BranchRepository) *string {
		if v == nil {
			return nil
		}
		return v.Host
	}).(pulumi.StringPtrOutput)
}

// URL of the repository.
func (o BranchRepositoryPtrOutput) Url() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *BranchRepository) *string {
		if v == nil {
			return nil
		}
		return &v.Url
	}).(pulumi.StringPtrOutput)
}

type BranchRepositoryAuth struct {
	// Token used to authenticate with the repository host.
	Token *string `pulumi:"token"`
}

// BranchRepositoryAuthInput is an input type that accepts BranchRepositoryAuthArgs and BranchRepositoryAuthOutput values.
// You can construct a concrete instance of `BranchRepositoryAuthInput` via:
//
//	BranchRepositoryAuthArgs{...}
type BranchRepositoryAuthInput interface {
	pulumi.Input

	ToBranchRepositoryAuthOutput() BranchRepositoryAuthOutput
	ToBranchRepositoryAuthOutputWithContext(context.Context) BranchRepositoryAuthOutput
}

type BranchRepositoryAuthArgs struct {
	// Token used to authenticate with the repository host.
	Token pulumi.StringPtrInput `pulumi:"token"`
}

func (BranchRepositoryAuthArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*BranchRepositoryAuth)(nil)).Elem()
}

func (i BranchRepositoryAuthArgs) ToBranchRepositoryAuthOutput() BranchRepositoryAuthOutput {
	return i.ToBranchRepositoryAuthOutputWithContext(context.Background())
}

func (i BranchRepositoryAuthArgs) ToBranchRepositoryAuthOutputWithContext(ctx context.Context) BranchRepositoryAuthOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BranchRepositoryAuthOutput)
}

func (i BranchRepositoryAuthArgs) ToBranchRepositoryAuthPtrOutput() BranchRepositoryAuthPtrOutput {
	return i.ToBranchRepositoryAuthPtrOutputWithContext(context.Background())
}

func (i BranchRepositoryAuthArgs) ToBranchRepositoryAuthPtrOutputWithContext(ctx context.Context) BranchRepositoryAuthPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BranchRepositoryAuthOutput).ToBranchRepositoryAuthPtrOutputWithContext(ctx)
}

// BranchRepositoryAuthPtrInput is an input type that accepts BranchRepositoryAuthArgs, BranchRepositoryAuthPtr and BranchRepositoryAuthPtrOutput values.
// You can construct a concrete instance of `BranchRepositoryAuthPtrInput` via:
//
//	        BranchRepositoryAuthArgs{...}
//
//	or:
//
//	        nil
type BranchRepositoryAuthPtrInput interface {
	pulumi.Input

	ToBranchRepositoryAuthPtrOutput() BranchRepositoryAuthPtrOutput
	ToBranchRepositoryAuthPtrOutputWithContext(context.Context) BranchRepositoryAuthPtrOutput
}

type branchRepositoryAuthPtrType BranchRepositoryAuthArgs

func BranchRepositoryAuthPtr(v *BranchRepositoryAuthArgs) BranchRepositoryAuthPtrInput {
	return (*branchRepositoryAuthPtrType)(v)
}

func (*branchRepositoryAuthPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**BranchRepositoryAuth)(nil)).Elem()
}

func (i *branchRepositoryAuthPtrType) ToBranchRepositoryAuthPtrOutput() BranchRepositoryAuthPtrOutput {
	return i.ToBranchRepositoryAuthPtrOutputWithContext(context.Background())
}

func (i *branchRepositoryAuthPtrType) ToBranchRepositoryAuthPtrOutputWithContext(ctx context.Context) BranchRepositoryAuthPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BranchRepositoryAuthPtrOutput)
}

type BranchRepositoryAuthOutput struct{ *pulumi.OutputState }

func (BranchRepositoryAuthOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*BranchRepositoryAuth)(nil)).Elem()
}

func (o BranchRepositoryAuthOutput) ToBranchRepositoryAuthOutput() BranchRepositoryAuthOutput {
	return o
}

func (o BranchRepositoryAuthOutput) ToBranchRepositoryAuthOutputWithContext(ctx context.Context) BranchRepositoryAuthOutput {
	return o
}

func (o BranchRepositoryAuthOutput) ToBranchRepositoryAuthPtrOutput() BranchRepositoryAuthPtrOutput {
	return o.ToBranchRepositoryAuthPtrOutputWithContext(context.Background())
}

func (o BranchRepositoryAuthOutput) ToBranchRepositoryAuthPtrOutputWithContext(ctx context.Context) BranchRepositoryAuthPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v BranchRepositoryAuth) *BranchRepositoryAuth {
		return &v
	}).(BranchRepositoryAuthPtrOutput)
}

// Token used to authenticate with the repository host.
func (o BranchRepositoryAuthOutput) Token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v BranchRepositoryAuth) *string { return v.Token }).(pulumi.StringPtrOutput)
}

type BranchRepositoryAuthPtrOutput struct{ *pulumi.OutputState }

func (BranchRepositoryAuthPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**BranchRepositoryAuth)(nil)).Elem()
}

func (o BranchRepositoryAuthPtrOutput) ToBranchRepositoryAuthPtrOutput() BranchRepositoryAuthPtrOutput {
	return o
}

func (o BranchRepositoryAuthPtrOutput) ToBranchRepositoryAuthPtrOutputWithContext(ctx context.Context) BranchRepositoryAuthPtrOutput {
	return o
}

func (o BranchRepositoryAuthPtrOutput) Elem() BranchRepositoryAuthOutput {
	return o.ApplyT(func(v *BranchRepositoryAuth) BranchRepositoryAuth {
		if v != nil {
			return *v
		}
		var ret BranchRepositoryAuth
		return ret
	}).(BranchRepositoryAuthOutput)
}

// Token used to authenticate with the repository host.
func (o BranchRepositoryAuthPtrOutput) Token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *BranchRepositoryAuth) *string {
		if v == nil {
			return nil
		}
		return v.Token
	}).(pulumi.StringPtrOutput)
}

type ProviderAuth struct {
	// Default token used to authenticate with a repository host, unless overridden per-resource.
	Token *string `pulumi:"token"`
}

// ProviderAuthInput is an input type that accepts ProviderAuthArgs and ProviderAuthOutput values.
// You can construct a concrete instance of `ProviderAuthInput` via:
//
//	ProviderAuthArgs{...}
type ProviderAuthInput interface {
	pulumi.Input

	ToProviderAuthOutput() ProviderAuthOutput
	ToProviderAuthOutputWithContext(context.Context) ProviderAuthOutput
}

type ProviderAuthArgs struct {
	// Default token used to authenticate with a repository host, unless overridden per-resource.
	Token pulumi.StringPtrInput `pulumi:"token"`
}

func (ProviderAuthArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ProviderAuth)(nil)).Elem()
}

func (i ProviderAuthArgs) ToProviderAuthOutput() ProviderAuthOutput {
	return i.ToProviderAuthOutputWithContext(context.Background())
}

func (i ProviderAuthArgs) ToProviderAuthOutputWithContext(ctx context.Context) ProviderAuthOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderAuthOutput)
}

func (i ProviderAuthArgs) ToProviderAuthPtrOutput() ProviderAuthPtrOutput {
	return i.ToProviderAuthPtrOutputWithContext(context.Background())
}

func (i ProviderAuthArgs) ToProviderAuthPtrOutputWithContext(ctx context.Context) ProviderAuthPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderAuthOutput).ToProviderAuthPtrOutputWithContext(ctx)
}

// ProviderAuthPtrInput is an input type that accepts ProviderAuthArgs, ProviderAuthPtr and ProviderAuthPtrOutput values.
// You can construct a concrete instance of `ProviderAuthPtrInput` via:
//
//	        ProviderAuthArgs{...}
//
//	or:
//
//	        nil
type ProviderAuthPtrInput interface {
	pulumi.Input

	ToProviderAuthPtrOutput() ProviderAuthPtrOutput
	ToProviderAuthPtrOutputWithContext(context.Context) ProviderAuthPtrOutput
}

type providerAuthPtrType ProviderAuthArgs

func ProviderAuthPtr(v *ProviderAuthArgs) ProviderAuthPtrInput {
	return (*providerAuthPtrType)(v)
}

func (*providerAuthPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ProviderAuth)(nil)).Elem()
}

func (i *providerAuthPtrType) ToProviderAuthPtrOutput() ProviderAuthPtrOutput {
	return i.ToProviderAuthPtrOutputWithContext(context.Background())
}

func (i *providerAuthPtrType) ToProviderAuthPtrOutputWithContext(ctx context.Context) ProviderAuthPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderAuthPtrOutput)
}

type ProviderAuthOutput struct{ *pulumi.OutputState }

func (ProviderAuthOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ProviderAuth)(nil)).Elem()
}

func (o ProviderAuthOutput) ToProviderAuthOutput() ProviderAuthOutput {
	return o
}

func (o ProviderAuthOutput) ToProviderAuthOutputWithContext(ctx context.Context) ProviderAuthOutput {
	return o
}

func (o ProviderAuthOutput) ToProviderAuthPtrOutput() ProviderAuthPtrOutput {
	return o.ToProviderAuthPtrOutputWithContext(context.Background())
}

func (o ProviderAuthOutput) ToProviderAuthPtrOutputWithContext(ctx context.Context) ProviderAuthPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ProviderAuth) *ProviderAuth {
		return &v
	}).(ProviderAuthPtrOutput)
}

// Default token used to authenticate with a repository host, unless overridden per-resource.
func (o ProviderAuthOutput) Token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ProviderAuth) *string { return v.Token }).(pulumi.StringPtrOutput)
}

type ProviderAuthPtrOutput struct{ *pulumi.OutputState }

func (ProviderAuthPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ProviderAuth)(nil)).Elem()
}

func (o ProviderAuthPtrOutput) ToProviderAuthPtrOutput() ProviderAuthPtrOutput {
	return o
}

func (o ProviderAuthPtrOutput) ToProviderAuthPtrOutputWithContext(ctx context.Context) ProviderAuthPtrOutput {
	return o
}

func (o ProviderAuthPtrOutput) Elem() ProviderAuthOutput {
	return o.ApplyT(func(v *ProviderAuth) ProviderAuth {
		if v != nil {
			return *v
		}
		var ret ProviderAuth
		return ret
	}).(ProviderAuthOutput)
}

// Default token used to authenticate with a repository host, unless overridden per-resource.
func (o ProviderAuthPtrOutput) Token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProviderAuth) *string {
		if v == nil {
			return nil
		}
		return v.Token
	}).(pulumi.StringPtrOutput)
}

type GetPatchAuth struct {
	// Token used to authenticate with the GitHub or GitLab API.
	Token *string `pulumi:"token"`
}

// GetPatchAuthInput is an input type that accepts GetPatchAuthArgs and GetPatchAuthOutput values.
// You can construct a concrete instance of `GetPatchAuthInput` via:
//
//	GetPatchAuthArgs{...}
type GetPatchAuthInput interface {
	pulumi.Input

	ToGetPatchAuthOutput() GetPatchAuthOutput
	ToGetPatchAuthOutputWithContext(context.Context) GetPatchAuthOutput
}

type GetPatchAuthArgs struct {
	// Token used to authenticate with the GitHub or GitLab API.
	Token pulumi.StringPtrInput `pulumi:"token"`
}

func (GetPatchAuthArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPatchAuth)(nil)).Elem()
}

func (i GetPatchAuthArgs) ToGetPatchAuthOutput() GetPatchAuthOutput {
	return i.ToGetPatchAuthOutputWithContext(context.Background())
}

func (i GetPatchAuthArgs) ToGetPatchAuthOutputWithContext(ctx context.Context) GetPatchAuthOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPatchAuthOutput)
}

func (i GetPatchAuthArgs) ToGetPatchAuthPtrOutput() GetPatchAuthPtrOutput {
	return i.ToGetPatchAuthPtrOutputWithContext(context.Background())
}

func (i GetPatchAuthArgs) ToGetPatchAuthPtrOutputWithContext(ctx context.Context) GetPatchAuthPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPatchAuthOutput).ToGetPatchAuthPtrOutputWithContext(ctx)
}

// GetPatchAuthPtrInput is an input type that accepts GetPatchAuthArgs, GetPatchAuthPtr and GetPatchAuthPtrOutput values.
// You can construct a concrete instance of `GetPatchAuthPtrInput` via:
//
//	        GetPatchAuthArgs{...}
//
//	or:
//
//	        nil
type GetPatchAuthPtrInput interface {
	pulumi.Input

	ToGetPatchAuthPtrOutput() GetPatchAuthPtrOutput
	ToGetPatchAuthPtrOutputWithContext(context.Context) GetPatchAuthPtrOutput
}

type getPatchAuthPtrType GetPatchAuthArgs

func GetPatchAuthPtr(v *GetPatchAuthArgs) GetPatchAuthPtrInput {
	return (*getPatchAuthPtrType)(v)
}

func (*getPatchAuthPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**GetPatchAuth)(nil)).Elem()
}

func (i *getPatchAuthPtrType) ToGetPatchAuthPtrOutput() GetPatchAuthPtrOutput {
	return i.ToGetPatchAuthPtrOutputWithContext(context.Background())
}

func (i *getPatchAuthPtrType) ToGetPatchAuthPtrOutputWithContext(ctx context.Context) GetPatchAuthPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPatchAuthPtrOutput)
}

type GetPatchAuthOutput struct{ *pulumi.OutputState }

func (GetPatchAuthOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPatchAuth)(nil)).Elem()
}

func (o GetPatchAuthOutput) ToGetPatchAuthOutput() GetPatchAuthOutput {
	return o
}

func (o GetPatchAuthOutput) ToGetPatchAuthOutputWithContext(ctx context.Context) GetPatchAuthOutput {
	return o
}

func (o GetPatchAuthOutput) ToGetPatchAuthPtrOutput() GetPatchAuthPtrOutput {
	return o.ToGetPatchAuthPtrOutputWithContext(context.Background())
}

func (o GetPatchAuthOutput) ToGetPatchAuthPtrOutputWithContext(ctx context.Context) GetPatchAuthPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v GetPatchAuth) *GetPatchAuth {
		return &v
	}).(GetPatchAuthPtrOutput)
}

// Token used to authenticate with the GitHub or GitLab API.
func (o GetPatchAuthOutput) Token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetPatchAuth) *string { return v.Token }).(pulumi.StringPtrOutput)
}

type GetPatchAuthPtrOutput struct{ *pulumi.OutputState }

func (GetPatchAuthPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GetPatchAuth)(nil)).Elem()
}

func (o GetPatchAuthPtrOutput) ToGetPatchAuthPtrOutput() GetPatchAuthPtrOutput {
	return o
}

func (o GetPatchAuthPtrOutput) ToGetPatchAuthPtrOutputWithContext(ctx context.Context) GetPatchAuthPtrOutput {
	return o
}

func (o GetPatchAuthPtrOutput) Elem() GetPatchAuthOutput {
	return o.ApplyT(func(v *GetPatchAuth) GetPatchAuth {
		if v != nil {
			return *v
		}
		var ret GetPatchAuth
		return ret
	}).(GetPatchAuthOutput)
}

// Token used to authenticate with the GitHub or GitLab API.
func (o GetPatchAuthPtrOutput) Token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GetPatchAuth) *string {
		if v == nil {
			return nil
		}
		return v.Token
	}).(pulumi.StringPtrOutput)
}

type GetPatchGithub struct {
	// Commit sha to resolve the patch from.
	Commit *string `pulumi:"commit"`
	// Pull request number to resolve the patch from.
	Pr *int `pulumi:"pr"`
	// Repository the pull request or commit belongs to, in `owner/name` form.
	Repository string `pulumi:"repository"`
	// Resolved commit sha (the pull request's head commit, or `commit` itself).
	Sha string `pulumi:"sha"`
}

// GetPatchGithubInput is an input type that accepts GetPatchGithubArgs and GetPatchGithubOutput values.
// You can construct a concrete instance of `GetPatchGithubInput` via:
//
//	GetPatchGithubArgs{...}
type GetPatchGithubInput interface {
	pulumi.Input

	ToGetPatchGithubOutput() GetPatchGithubOutput
	ToGetPatchGithubOutputWithContext(context.Context) GetPatchGithubOutput
}

type GetPatchGithubArgs struct {
	// Commit sha to resolve the patch from.
	Commit pulumi.StringPtrInput `pulumi:"commit"`
	// Pull request number to resolve the patch from.
	Pr pulumi.IntPtrInput `pulumi:"pr"`
	// Repository the pull request or commit belongs to, in `owner/name` form.
	Repository pulumi.StringInput `pulumi:"repository"`
	// Resolved commit sha (the pull request's head commit, or `commit` itself).
	Sha pulumi.StringInput `pulumi:"sha"`
}

func (GetPatchGithubArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPatchGithub)(nil)).Elem()
}

func (i GetPatchGithubArgs) ToGetPatchGithubOutput() GetPatchGithubOutput {
	return i.ToGetPatchGithubOutputWithContext(context.Background())
}

func (i GetPatchGithubArgs) ToGetPatchGithubOutputWithContext(ctx context.Context) GetPatchGithubOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPatchGithubOutput)
}

func (i GetPatchGithubArgs) ToGetPatchGithubPtrOutput() GetPatchGithubPtrOutput {
	return i.ToGetPatchGithubPtrOutputWithContext(context.Background())
}

func (i GetPatchGithubArgs) ToGetPatchGithubPtrOutputWithContext(ctx context.Context) GetPatchGithubPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPatchGithubOutput).ToGetPatchGithubPtrOutputWithContext(ctx)
}

// GetPatchGithubPtrInput is an input type that accepts GetPatchGithubArgs, GetPatchGithubPtr and GetPatchGithubPtrOutput values.
// You can construct a concrete instance of `GetPatchGithubPtrInput` via:
//
//	        GetPatchGithubArgs{...}
//
//	or:
//
//	        nil
type GetPatchGithubPtrInput interface {
	pulumi.Input

	ToGetPatchGithubPtrOutput() GetPatchGithubPtrOutput
	ToGetPatchGithubPtrOutputWithContext(context.Context) GetPatchGithubPtrOutput
}

type getPatchGithubPtrType GetPatchGithubArgs

func GetPatchGithubPtr(v *GetPatchGithubArgs) GetPatchGithubPtrInput {
	return (*getPatchGithubPtrType)(v)
}

func (*getPatchGithubPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**GetPatchGithub)(nil)).Elem()
}

func (i *getPatchGithubPtrType) ToGetPatchGithubPtrOutput() GetPatchGithubPtrOutput {
	return i.ToGetPatchGithubPtrOutputWithContext(context.Background())
}

func (i *getPatchGithubPtrType) ToGetPatchGithubPtrOutputWithContext(ctx context.Context) GetPatchGithubPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPatchGithubPtrOutput)
}

type GetPatchGithubOutput struct{ *pulumi.OutputState }

func (GetPatchGithubOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPatchGithub)(nil)).Elem()
}

func (o GetPatchGithubOutput) ToGetPatchGithubOutput() GetPatchGithubOutput {
	return o
}

func (o GetPatchGithubOutput) ToGetPatchGithubOutputWithContext(ctx context.Context) GetPatchGithubOutput {
	return o
}

func (o GetPatchGithubOutput) ToGetPatchGithubPtrOutput() GetPatchGithubPtrOutput {
	return o.ToGetPatchGithubPtrOutputWithContext(context.Background())
}

func (o GetPatchGithubOutput) ToGetPatchGithubPtrOutputWithContext(ctx context.Context) GetPatchGithubPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v GetPatchGithub) *GetPatchGithub {
		return &v
	}).(GetPatchGithubPtrOutput)
}

// Commit sha to resolve the patch from.
func (o GetPatchGithubOutput) Commit() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetPatchGithub) *string { return v.Commit }).(pulumi.StringPtrOutput)
}

// Pull request number to resolve the patch from.
func (o GetPatchGithubOutput) Pr() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetPatchGithub) *int { return v.Pr }).(pulumi.IntPtrOutput)
}

// Repository the pull request or commit belongs to, in `owner/name` form.
func (o GetPatchGithubOutput) Repository() pulumi.StringOutput {
	return o.ApplyT(func(v GetPatchGithub) string { return v.Repository }).(pulumi.StringOutput)
}

// Resolved commit sha (the pull request's head commit, or `commit` itself).
func (o GetPatchGithubOutput) Sha() pulumi.StringOutput {
	return o.ApplyT(func(v GetPatchGithub) string { return v.Sha }).(pulumi.StringOutput)
}

type GetPatchGithubPtrOutput struct{ *pulumi.OutputState }

func (GetPatchGithubPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GetPatchGithub)(nil)).Elem()
}

func (o GetPatchGithubPtrOutput) ToGetPatchGithubPtrOutput() GetPatchGithubPtrOutput {
	return o
}

func (o GetPatchGithubPtrOutput) ToGetPatchGithubPtrOutputWithContext(ctx context.Context) GetPatchGithubPtrOutput {
	return o
}

func (o GetPatchGithubPtrOutput) Elem() GetPatchGithubOutput {
	return o.ApplyT(func(v *GetPatchGithub) GetPatchGithub {
		if v != nil {
			return *v
		}
		var ret GetPatchGithub
		return ret
	}).(GetPatchGithubOutput)
}

// Commit sha to resolve the patch from.
func (o GetPatchGithubPtrOutput) Commit() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GetPatchGithub) *string {
		if v == nil {
			return nil
		}
		return v.Commit
	}).(pulumi.StringPtrOutput)
}

// Pull request number to resolve the patch from.
func (o GetPatchGithubPtrOutput) Pr() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *GetPatchGithub) *int {
		if v == nil {
			return nil
		}
		return v.Pr
	}).(pulumi.IntPtrOutput)
}

// Repository the pull request or commit belongs to, in `owner/name` form.
func (o GetPatchGithubPtrOutput) Repository() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GetPatchGithub) *string {
		if v == nil {
			return nil
		}
		return &v.Repository
	}).(pulumi.StringPtrOutput)
}

// Resolved commit sha (the pull request's head commit, or `commit` itself).
func (o GetPatchGithubPtrOutput) Sha() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GetPatchGithub) *string {
		if v == nil {
			return nil
		}
		return &v.Sha
	}).(pulumi.StringPtrOutput)
}

type GetPatchGitlab struct {
	// Commit sha to resolve the patch from.
	Commit *string `pulumi:"commit"`
	// Merge request IID to resolve the patch from.
	Mr *int `pulumi:"mr"`
	// Project the merge request or commit belongs to, as a GitLab project path (e.g. `group/project`) or numeric ID.
	Project string `pulumi:"project"`
	// Resolved commit sha (the merge request's head commit, or `commit` itself).
	Sha string `pulumi:"sha"`
}

// GetPatchGitlabInput is an input type that accepts GetPatchGitlabArgs and GetPatchGitlabOutput values.
// You can construct a concrete instance of `GetPatchGitlabInput` via:
//
//	GetPatchGitlabArgs{...}
type GetPatchGitlabInput interface {
	pulumi.Input

	ToGetPatchGitlabOutput() GetPatchGitlabOutput
	ToGetPatchGitlabOutputWithContext(context.Context) GetPatchGitlabOutput
}

type GetPatchGitlabArgs struct {
	// Commit sha to resolve the patch from.
	Commit pulumi.StringPtrInput `pulumi:"commit"`
	// Merge request IID to resolve the patch from.
	Mr pulumi.IntPtrInput `pulumi:"mr"`
	// Project the merge request or commit belongs to, as a GitLab project path (e.g. `group/project`) or numeric ID.
	Project pulumi.StringInput `pulumi:"project"`
	// Resolved commit sha (the merge request's head commit, or `commit` itself).
	Sha pulumi.StringInput `pulumi:"sha"`
}

func (GetPatchGitlabArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPatchGitlab)(nil)).Elem()
}

func (i GetPatchGitlabArgs) ToGetPatchGitlabOutput() GetPatchGitlabOutput {
	return i.ToGetPatchGitlabOutputWithContext(context.Background())
}

func (i GetPatchGitlabArgs) ToGetPatchGitlabOutputWithContext(ctx context.Context) GetPatchGitlabOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPatchGitlabOutput)
}

func (i GetPatchGitlabArgs) ToGetPatchGitlabPtrOutput() GetPatchGitlabPtrOutput {
	return i.ToGetPatchGitlabPtrOutputWithContext(context.Background())
}

func (i GetPatchGitlabArgs) ToGetPatchGitlabPtrOutputWithContext(ctx context.Context) GetPatchGitlabPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPatchGitlabOutput).ToGetPatchGitlabPtrOutputWithContext(ctx)
}

// GetPatchGitlabPtrInput is an input type that accepts GetPatchGitlabArgs, GetPatchGitlabPtr and GetPatchGitlabPtrOutput values.
// You can construct a concrete instance of `GetPatchGitlabPtrInput` via:
//
//	        GetPatchGitlabArgs{...}
//
//	or:
//
//	        nil
type GetPatchGitlabPtrInput interface {
	pulumi.Input

	ToGetPatchGitlabPtrOutput() GetPatchGitlabPtrOutput
	ToGetPatchGitlabPtrOutputWithContext(context.Context) GetPatchGitlabPtrOutput
}

type getPatchGitlabPtrType GetPatchGitlabArgs

func GetPatchGitlabPtr(v *GetPatchGitlabArgs) GetPatchGitlabPtrInput {
	return (*getPatchGitlabPtrType)(v)
}

func (*getPatchGitlabPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**GetPatchGitlab)(nil)).Elem()
}

func (i *getPatchGitlabPtrType) ToGetPatchGitlabPtrOutput() GetPatchGitlabPtrOutput {
	return i.ToGetPatchGitlabPtrOutputWithContext(context.Background())
}

func (i *getPatchGitlabPtrType) ToGetPatchGitlabPtrOutputWithContext(ctx context.Context) GetPatchGitlabPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPatchGitlabPtrOutput)
}

type GetPatchGitlabOutput struct{ *pulumi.OutputState }

func (GetPatchGitlabOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPatchGitlab)(nil)).Elem()
}

func (o GetPatchGitlabOutput) ToGetPatchGitlabOutput() GetPatchGitlabOutput {
	return o
}

func (o GetPatchGitlabOutput) ToGetPatchGitlabOutputWithContext(ctx context.Context) GetPatchGitlabOutput {
	return o
}

func (o GetPatchGitlabOutput) ToGetPatchGitlabPtrOutput() GetPatchGitlabPtrOutput {
	return o.ToGetPatchGitlabPtrOutputWithContext(context.Background())
}

func (o GetPatchGitlabOutput) ToGetPatchGitlabPtrOutputWithContext(ctx context.Context) GetPatchGitlabPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v GetPatchGitlab) *GetPatchGitlab {
		return &v
	}).(GetPatchGitlabPtrOutput)
}

// Commit sha to resolve the patch from.
func (o GetPatchGitlabOutput) Commit() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetPatchGitlab) *string { return v.Commit }).(pulumi.StringPtrOutput)
}

// Merge request IID to resolve the patch from.
func (o GetPatchGitlabOutput) Mr() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetPatchGitlab) *int { return v.Mr }).(pulumi.IntPtrOutput)
}

// Project the merge request or commit belongs to, as a GitLab project path (e.g. `group/project`) or numeric ID.
func (o GetPatchGitlabOutput) Project() pulumi.StringOutput {
	return o.ApplyT(func(v GetPatchGitlab) string { return v.Project }).(pulumi.StringOutput)
}

// Resolved commit sha (the merge request's head commit, or `commit` itself).
func (o GetPatchGitlabOutput) Sha() pulumi.StringOutput {
	return o.ApplyT(func(v GetPatchGitlab) string { return v.Sha }).(pulumi.StringOutput)
}

type GetPatchGitlabPtrOutput struct{ *pulumi.OutputState }

func (GetPatchGitlabPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GetPatchGitlab)(nil)).Elem()
}

func (o GetPatchGitlabPtrOutput) ToGetPatchGitlabPtrOutput() GetPatchGitlabPtrOutput {
	return o
}

func (o GetPatchGitlabPtrOutput) ToGetPatchGitlabPtrOutputWithContext(ctx context.Context) GetPatchGitlabPtrOutput {
	return o
}

func (o GetPatchGitlabPtrOutput) Elem() GetPatchGitlabOutput {
	return o.ApplyT(func(v *GetPatchGitlab) GetPatchGitlab {
		if v != nil {
			return *v
		}
		var ret GetPatchGitlab
		return ret
	}).(GetPatchGitlabOutput)
}

// Commit sha to resolve the patch from.
func (o GetPatchGitlabPtrOutput) Commit() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GetPatchGitlab) *string {
		if v == nil {
			return nil
		}
		return v.Commit
	}).(pulumi.StringPtrOutput)
}

// Merge request IID to resolve the patch from.
func (o GetPatchGitlabPtrOutput) Mr() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *GetPatchGitlab) *int {
		if v == nil {
			return nil
		}
		return v.Mr
	}).(pulumi.IntPtrOutput)
}

// Project the merge request or commit belongs to, as a GitLab project path (e.g. `group/project`) or numeric ID.
func (o GetPatchGitlabPtrOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GetPatchGitlab) *string {
		if v == nil {
			return nil
		}
		return &v.Project
	}).(pulumi.StringPtrOutput)
}

// Resolved commit sha (the merge request's head commit, or `commit` itself).
func (o GetPatchGitlabPtrOutput) Sha() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GetPatchGitlab) *string {
		if v == nil {
			return nil
		}
		return &v.Sha
	}).(pulumi.StringPtrOutput)
}

type GetRepositoryAuth struct {
	// Token used to authenticate with the repository host.
	Token *string `pulumi:"token"`
}

// GetRepositoryAuthInput is an input type that accepts GetRepositoryAuthArgs and GetRepositoryAuthOutput values.
// You can construct a concrete instance of `GetRepositoryAuthInput` via:
//
//	GetRepositoryAuthArgs{...}
type GetRepositoryAuthInput interface {
	pulumi.Input

	ToGetRepositoryAuthOutput() GetRepositoryAuthOutput
	ToGetRepositoryAuthOutputWithContext(context.Context) GetRepositoryAuthOutput
}

type GetRepositoryAuthArgs struct {
	// Token used to authenticate with the repository host.
	Token pulumi.StringPtrInput `pulumi:"token"`
}

func (GetRepositoryAuthArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetRepositoryAuth)(nil)).Elem()
}

func (i GetRepositoryAuthArgs) ToGetRepositoryAuthOutput() GetRepositoryAuthOutput {
	return i.ToGetRepositoryAuthOutputWithContext(context.Background())
}

func (i GetRepositoryAuthArgs) ToGetRepositoryAuthOutputWithContext(ctx context.Context) GetRepositoryAuthOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetRepositoryAuthOutput)
}

func (i GetRepositoryAuthArgs) ToGetRepositoryAuthPtrOutput() GetRepositoryAuthPtrOutput {
	return i.ToGetRepositoryAuthPtrOutputWithContext(context.Background())
}

func (i GetRepositoryAuthArgs) ToGetRepositoryAuthPtrOutputWithContext(ctx context.Context) GetRepositoryAuthPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetRepositoryAuthOutput).ToGetRepositoryAuthPtrOutputWithContext(ctx)
}

// GetRepositoryAuthPtrInput is an input type that accepts GetRepositoryAuthArgs, GetRepositoryAuthPtr and GetRepositoryAuthPtrOutput values.
// You can construct a concrete instance of `GetRepositoryAuthPtrInput` via:
//
//	        GetRepositoryAuthArgs{...}
//
//	or:
//
//	        nil
type GetRepositoryAuthPtrInput interface {
	pulumi.Input

	ToGetRepositoryAuthPtrOutput() GetRepositoryAuthPtrOutput
	ToGetRepositoryAuthPtrOutputWithContext(context.Context) GetRepositoryAuthPtrOutput
}

type getRepositoryAuthPtrType GetRepositoryAuthArgs

func GetRepositoryAuthPtr(v *GetRepositoryAuthArgs) GetRepositoryAuthPtrInput {
	return (*getRepositoryAuthPtrType)(v)
}

func (*getRepositoryAuthPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**GetRepositoryAuth)(nil)).Elem()
}

func (i *getRepositoryAuthPtrType) ToGetRepositoryAuthPtrOutput() GetRepositoryAuthPtrOutput {
	return i.ToGetRepositoryAuthPtrOutputWithContext(context.Background())
}

func (i *getRepositoryAuthPtrType) ToGetRepositoryAuthPtrOutputWithContext(ctx context.Context) GetRepositoryAuthPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetRepositoryAuthPtrOutput)
}

type GetRepositoryAuthOutput struct{ *pulumi.OutputState }

func (GetRepositoryAuthOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetRepositoryAuth)(nil)).Elem()
}

func (o GetRepositoryAuthOutput) ToGetRepositoryAuthOutput() GetRepositoryAuthOutput {
	return o
}

func (o GetRepositoryAuthOutput) ToGetRepositoryAuthOutputWithContext(ctx context.Context) GetRepositoryAuthOutput {
	return o
}

func (o GetRepositoryAuthOutput) ToGetRepositoryAuthPtrOutput() GetRepositoryAuthPtrOutput {
	return o.ToGetRepositoryAuthPtrOutputWithContext(context.Background())
}

func (o GetRepositoryAuthOutput) ToGetRepositoryAuthPtrOutputWithContext(ctx context.Context) GetRepositoryAuthPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v GetRepositoryAuth) *GetRepositoryAuth {
		return &v
	}).(GetRepositoryAuthPtrOutput)
}

// Token used to authenticate with the repository host.
func (o GetRepositoryAuthOutput) Token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetRepositoryAuth) *string { return v.Token }).(pulumi.StringPtrOutput)
}

type GetRepositoryAuthPtrOutput struct{ *pulumi.OutputState }

func (GetRepositoryAuthPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GetRepositoryAuth)(nil)).Elem()
}

func (o GetRepositoryAuthPtrOutput) ToGetRepositoryAuthPtrOutput() GetRepositoryAuthPtrOutput {
	return o
}

func (o GetRepositoryAuthPtrOutput) ToGetRepositoryAuthPtrOutputWithContext(ctx context.Context) GetRepositoryAuthPtrOutput {
	return o
}

func (o GetRepositoryAuthPtrOutput) Elem() GetRepositoryAuthOutput {
	return o.ApplyT(func(v *GetRepositoryAuth) GetRepositoryAuth {
		if v != nil {
			return *v
		}
		var ret GetRepositoryAuth
		return ret
	}).(GetRepositoryAuthOutput)
}

// Token used to authenticate with the repository host.
func (o GetRepositoryAuthPtrOutput) Token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GetRepositoryAuth) *string {
		if v == nil {
			return nil
		}
		return v.Token
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*BranchRepositoryInput)(nil)).Elem(), BranchRepositoryArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*BranchRepositoryPtrInput)(nil)).Elem(), BranchRepositoryArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*BranchRepositoryAuthInput)(nil)).Elem(), BranchRepositoryAuthArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*BranchRepositoryAuthPtrInput)(nil)).Elem(), BranchRepositoryAuthArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderAuthInput)(nil)).Elem(), ProviderAuthArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderAuthPtrInput)(nil)).Elem(), ProviderAuthArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPatchAuthInput)(nil)).Elem(), GetPatchAuthArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPatchAuthPtrInput)(nil)).Elem(), GetPatchAuthArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPatchGithubInput)(nil)).Elem(), GetPatchGithubArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPatchGithubPtrInput)(nil)).Elem(), GetPatchGithubArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPatchGitlabInput)(nil)).Elem(), GetPatchGitlabArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPatchGitlabPtrInput)(nil)).Elem(), GetPatchGitlabArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetRepositoryAuthInput)(nil)).Elem(), GetRepositoryAuthArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetRepositoryAuthPtrInput)(nil)).Elem(), GetRepositoryAuthArgs{})
	pulumi.RegisterOutputType(BranchRepositoryOutput{})
	pulumi.RegisterOutputType(BranchRepositoryPtrOutput{})
	pulumi.RegisterOutputType(BranchRepositoryAuthOutput{})
	pulumi.RegisterOutputType(BranchRepositoryAuthPtrOutput{})
	pulumi.RegisterOutputType(ProviderAuthOutput{})
	pulumi.RegisterOutputType(ProviderAuthPtrOutput{})
	pulumi.RegisterOutputType(GetPatchAuthOutput{})
	pulumi.RegisterOutputType(GetPatchAuthPtrOutput{})
	pulumi.RegisterOutputType(GetPatchGithubOutput{})
	pulumi.RegisterOutputType(GetPatchGithubPtrOutput{})
	pulumi.RegisterOutputType(GetPatchGitlabOutput{})
	pulumi.RegisterOutputType(GetPatchGitlabPtrOutput{})
	pulumi.RegisterOutputType(GetRepositoryAuthOutput{})
	pulumi.RegisterOutputType(GetRepositoryAuthPtrOutput{})
}
