// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Tracks a branch's base ref within a repository, and optionally an ordered patch stack applied on top of it. When `patches` is set, the resulting commits are force-pushed to the branch on the remote; otherwise this resource only resolves and tracks the observed base ref.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as git from "@unmango/pulumi-git";
 *
 * // Omits the required_providers block since this example also runs as an
 * // acceptance test against an in-process build; see examples/provider/provider.tf.
 * // Tracks the "main" branch of a public repository. Safe to run against a
 * // repository you don't own; git_branch never pushes.
 * const main = new git.Branch("main", {
 *     repository: {
 *         url: "https://github.com/UnstoppableMango/terraform-provider-git.git",
 *         host: "github",
 *     },
 *     name: "main",
 *     baseRef: "main",
 * });
 * export const resolvedSha = main.baseSha;
 * ```
 */
export class Branch extends pulumi.CustomResource {
    /**
     * Get an existing Branch resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: BranchState, opts?: pulumi.CustomResourceOptions): Branch {
        return new Branch(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'git:index/branch:Branch';

    /**
     * Returns true if the given object is an instance of Branch.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Branch {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Branch.__pulumiType;
    }

    /**
     * Ref this branch is based on.
     */
    declare public readonly baseRef: pulumi.Output<string>;
    /**
     * Resolved commit hash of `baseRef` as of the last read.
     */
    declare public /*out*/ readonly baseSha: pulumi.Output<string>;
    /**
     * Name of the branch.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * How to handle the branch's remote tip having moved since it was last observed, when pushing the patch stack. `force` (default) always force-pushes, discarding drift, matching this provider's historical behavior. `fail` aborts the push instead of clobbering unexpected remote changes; re-run `pulumi up` to pick up the new tip, or resolve the drift manually. Only takes effect when `patches` is set. Must be one of `fail` or `force`.
     */
    declare public readonly onConflict: pulumi.Output<string>;
    /**
     * Ordered list of patch diffs applied on top of base_ref, in the spirit of quilt push. When set, the resulting commits are force-pushed to the branch on the remote.
     */
    declare public readonly patches: pulumi.Output<string[] | undefined>;
    /**
     * Repository the branch belongs to.
     */
    declare public readonly repository: pulumi.Output<outputs.BranchRepository>;
    /**
     * Resolved commit hash the branch currently tracks.
     */
    declare public /*out*/ readonly resolvedRef: pulumi.Output<string>;

    /**
     * Create a Branch resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BranchArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: BranchArgs | BranchState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as BranchState | undefined;
            resourceInputs["baseRef"] = state?.baseRef;
            resourceInputs["baseSha"] = state?.baseSha;
            resourceInputs["name"] = state?.name;
            resourceInputs["onConflict"] = state?.onConflict;
            resourceInputs["patches"] = state?.patches;
            resourceInputs["repository"] = state?.repository;
            resourceInputs["resolvedRef"] = state?.resolvedRef;
        } else {
            const args = argsOrState as BranchArgs | undefined;
            if (args?.baseRef === undefined && !opts.urn) {
                throw new Error("Missing required property 'baseRef'");
            }
            if (args?.repository === undefined && !opts.urn) {
                throw new Error("Missing required property 'repository'");
            }
            resourceInputs["baseRef"] = args?.baseRef;
            resourceInputs["name"] = args?.name;
            resourceInputs["onConflict"] = args?.onConflict;
            resourceInputs["patches"] = args?.patches;
            resourceInputs["repository"] = args?.repository;
            resourceInputs["baseSha"] = undefined /*out*/;
            resourceInputs["resolvedRef"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Branch.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Branch resources.
 */
export interface BranchState {
    /**
     * Ref this branch is based on.
     */
    baseRef?: pulumi.Input<string | undefined>;
    /**
     * Resolved commit hash of `baseRef` as of the last read.
     */
    baseSha?: pulumi.Input<string | undefined>;
    /**
     * Name of the branch.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * How to handle the branch's remote tip having moved since it was last observed, when pushing the patch stack. `force` (default) always force-pushes, discarding drift, matching this provider's historical behavior. `fail` aborts the push instead of clobbering unexpected remote changes; re-run `pulumi up` to pick up the new tip, or resolve the drift manually. Only takes effect when `patches` is set. Must be one of `fail` or `force`.
     */
    onConflict?: pulumi.Input<string | undefined>;
    /**
     * Ordered list of patch diffs applied on top of base_ref, in the spirit of quilt push. When set, the resulting commits are force-pushed to the branch on the remote.
     */
    patches?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Repository the branch belongs to.
     */
    repository?: pulumi.Input<inputs.BranchRepository | undefined>;
    /**
     * Resolved commit hash the branch currently tracks.
     */
    resolvedRef?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Branch resource.
 */
export interface BranchArgs {
    /**
     * Ref this branch is based on.
     */
    baseRef: pulumi.Input<string>;
    /**
     * Name of the branch.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * How to handle the branch's remote tip having moved since it was last observed, when pushing the patch stack. `force` (default) always force-pushes, discarding drift, matching this provider's historical behavior. `fail` aborts the push instead of clobbering unexpected remote changes; re-run `pulumi up` to pick up the new tip, or resolve the drift manually. Only takes effect when `patches` is set. Must be one of `fail` or `force`.
     */
    onConflict?: pulumi.Input<string | undefined>;
    /**
     * Ordered list of patch diffs applied on top of base_ref, in the spirit of quilt push. When set, the resulting commits are force-pushed to the branch on the remote.
     */
    patches?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Repository the branch belongs to.
     */
    repository: pulumi.Input<inputs.BranchRepository>;
}
