// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Resolves a single patch: a local file, inline diff content, or a remote host source (e.g. a GitHub PR/commit or a GitLab MR/commit). Exactly one of `content`, `file`, `github`, or `gitlab` must be set. Does not clone, apply, commit, or push; that is `git.Branch`'s responsibility.
 */
export function getPatch(args?: GetPatchArgs, opts?: pulumi.InvokeOptions): Promise<GetPatchResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("git:index/getPatch:getPatch", {
        "auth": args.auth,
        "content": args.content,
        "file": args.file,
        "github": args.github,
        "gitlab": args.gitlab,
    }, opts);
}

/**
 * A collection of arguments for invoking getPatch.
 */
export interface GetPatchArgs {
    /**
     * Authentication details used to call the GitHub or GitLab API when `github` or `gitlab` is set.
     */
    auth?: inputs.GetPatchAuth;
    /**
     * Inline unified diff content.
     */
    content?: string;
    /**
     * Path to a local patch file, read on refresh.
     */
    file?: string;
    /**
     * Resolves the patch from a GitHub pull request or commit. Exactly one of `pr` or `commit` must be set.
     */
    github?: inputs.GetPatchGithub;
    /**
     * Resolves the patch from a GitLab merge request or commit. Exactly one of `mr` or `commit` must be set.
     */
    gitlab?: inputs.GetPatchGitlab;
}

/**
 * A collection of values returned by getPatch.
 */
export interface GetPatchResult {
    /**
     * Authentication details used to call the GitHub or GitLab API when `github` or `gitlab` is set.
     */
    readonly auth?: outputs.GetPatchAuth;
    /**
     * Inline unified diff content.
     */
    readonly content?: string;
    /**
     * Resolved unified diff content, from whichever of `content`, `file`, or `github` was set.
     */
    readonly diff: string;
    /**
     * Path to a local patch file, read on refresh.
     */
    readonly file?: string;
    /**
     * Resolves the patch from a GitHub pull request or commit. Exactly one of `pr` or `commit` must be set.
     */
    readonly github?: outputs.GetPatchGithub;
    /**
     * Resolves the patch from a GitLab merge request or commit. Exactly one of `mr` or `commit` must be set.
     */
    readonly gitlab?: outputs.GetPatchGitlab;
    /**
     * Stable identifier for the patch: the hex-encoded sha256 of the resolved `diff`.
     */
    readonly id: string;
}
/**
 * Resolves a single patch: a local file, inline diff content, or a remote host source (e.g. a GitHub PR/commit or a GitLab MR/commit). Exactly one of `content`, `file`, `github`, or `gitlab` must be set. Does not clone, apply, commit, or push; that is `git.Branch`'s responsibility.
 */
export function getPatchOutput(args?: GetPatchOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPatchResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("git:index/getPatch:getPatch", {
        "auth": args.auth,
        "content": args.content,
        "file": args.file,
        "github": args.github,
        "gitlab": args.gitlab,
    }, opts);
}

/**
 * A collection of arguments for invoking getPatch.
 */
export interface GetPatchOutputArgs {
    /**
     * Authentication details used to call the GitHub or GitLab API when `github` or `gitlab` is set.
     */
    auth?: pulumi.Input<inputs.GetPatchAuthArgs | undefined>;
    /**
     * Inline unified diff content.
     */
    content?: pulumi.Input<string | undefined>;
    /**
     * Path to a local patch file, read on refresh.
     */
    file?: pulumi.Input<string | undefined>;
    /**
     * Resolves the patch from a GitHub pull request or commit. Exactly one of `pr` or `commit` must be set.
     */
    github?: pulumi.Input<inputs.GetPatchGithubArgs | undefined>;
    /**
     * Resolves the patch from a GitLab merge request or commit. Exactly one of `mr` or `commit` must be set.
     */
    gitlab?: pulumi.Input<inputs.GetPatchGitlabArgs | undefined>;
}
