// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * References an existing repository. Reference-only: this provider never creates or deletes repositories on the host. It resolves connection details (URL, host type, auth) used by other resources.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as git from "@unmango/pulumi-git";
 *
 * // Omits the required_providers block since this example also runs as an
 * // acceptance test against an in-process build; see examples/provider/provider.tf.
 * // Resolves and verifies a public repository via ls-remote.
 * const _this = git.getRepository({
 *     url: "https://github.com/UnstoppableMango/terraform-provider-git.git",
 *     host: "github",
 * });
 * export const repositoryId = _this.then(_this => _this.id);
 * ```
 */
export function getRepository(args: GetRepositoryArgs, opts?: pulumi.InvokeOptions): Promise<GetRepositoryResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("git:index/getRepository:getRepository", {
        "auth": args.auth,
        "host": args.host,
        "url": args.url,
    }, opts);
}

/**
 * A collection of arguments for invoking getRepository.
 */
export interface GetRepositoryArgs {
    /**
     * Authentication details used to connect to the repository.
     */
    auth?: inputs.GetRepositoryAuth;
    /**
     * Type of host the repository is on. Must be one of `github`, `gitlab`, or `generic`.
     */
    host?: string;
    /**
     * URL of the repository.
     */
    url: string;
}

/**
 * A collection of values returned by getRepository.
 */
export interface GetRepositoryResult {
    /**
     * Authentication details used to connect to the repository.
     */
    readonly auth?: outputs.GetRepositoryAuth;
    /**
     * Type of host the repository is on. Must be one of `github`, `gitlab`, or `generic`.
     */
    readonly host?: string;
    /**
     * Identifier for the repository. Mirrors the `url` attribute.
     */
    readonly id: string;
    /**
     * URL of the repository.
     */
    readonly url: string;
}
/**
 * References an existing repository. Reference-only: this provider never creates or deletes repositories on the host. It resolves connection details (URL, host type, auth) used by other resources.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as git from "@unmango/pulumi-git";
 *
 * // Omits the required_providers block since this example also runs as an
 * // acceptance test against an in-process build; see examples/provider/provider.tf.
 * // Resolves and verifies a public repository via ls-remote.
 * const _this = git.getRepository({
 *     url: "https://github.com/UnstoppableMango/terraform-provider-git.git",
 *     host: "github",
 * });
 * export const repositoryId = _this.then(_this => _this.id);
 * ```
 */
export function getRepositoryOutput(args: GetRepositoryOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRepositoryResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("git:index/getRepository:getRepository", {
        "auth": args.auth,
        "host": args.host,
        "url": args.url,
    }, opts);
}

/**
 * A collection of arguments for invoking getRepository.
 */
export interface GetRepositoryOutputArgs {
    /**
     * Authentication details used to connect to the repository.
     */
    auth?: pulumi.Input<inputs.GetRepositoryAuthArgs | undefined>;
    /**
     * Type of host the repository is on. Must be one of `github`, `gitlab`, or `generic`.
     */
    host?: pulumi.Input<string | undefined>;
    /**
     * URL of the repository.
     */
    url: pulumi.Input<string>;
}
